In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
%matplotlib inline

In [2]:
df1 = pd.read_csv('./data/H_data/T20_2019_1백만.1.csv', encoding='cp949')
df2 = pd.read_csv('./data/H_data/T20_2019_1백만.2.csv', encoding='cp949')
df3 = pd.read_csv('./data/H_data/T20_2019_1백만.3.csv', encoding='cp949')
df4 = pd.read_csv('./data/H_data/HP_T20_2020_1.CSV', encoding='cp949')
df5 = pd.read_csv('./data/H_data/HP_T20_2020_2.CSV', encoding='cp949')
df6 = pd.read_csv('./data/H_data/HP_T20_2020_3.CSV', encoding='cp949')

In [4]:
data = pd.concat([df1,df2,df3,df4,df5,df6], ignore_index=True)

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24905593 entries, 0 to 24905592
Data columns (total 19 columns):
 #   Column      Dtype
---  ------      -----
 0   기준년도        int64
 1   가입자 일련번호    int64
 2   진료내역일련번호    int64
 3   성별코드        int64
 4   연령대코드       int64
 5   시도코드        int64
 6   요양개시일자      object
 7   서식코드        int64
 8   진료과목코드      int64
 9   주상병코드       object
 10  부상병코드       object
 11  요양일수        int64
 12  입내원일수       int64
 13  심결가산율       float64
 14  심결요양급여비용총액  int64
 15  심결본인부담금     int64
 16  심결보험자부담금    int64
 17  총처방일수       int64
 18  데이터 기준일자    object
dtypes: float64(1), int64(14), object(4)
memory usage: 3.5+ GB

In [5]:
var_list = ['성별코드', '연령대코드', '진료과목코드', '주상병코드', '부상병코드', '입내원일수']
data_1920 = data[var_list]
data_1920.head()

   성별코드  연령대코드  진료과목코드  주상병코드  부상병코드  입내원일수
0     2     12       5   M751   M750      1
1     2     12       1  E1164   N308      1
2     2     12       1   N308  E1164      1
3     2     12       1  E1164   N308     21
4     2     12      13  H6531   J303      1

In [6]:
from sklearn.naive_bayes import GaussianNB

In [7]:
gaussian_model = GaussianNB()

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(data_1920.iloc[:,1:-3], data_1920['성별코드'], test_size = 0.33)

In [3]:
# gaussian_model.fit(X_train, y_train)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, gaussian_model.predict(X_test)))

In [12]:
data_1920

          성별코드  연령대코드  시도코드  진료과목코드  주상병코드  부상병코드  입내원일수  총처방일수
0            2     12    46       5   M751   M750      1      0
1            2     12    46       1  E1164   N308      1      0
2            2     12    46       1   N308  E1164      1      3
3            2     12    46       1  E1164   N308     21      0
4            2     12    46      13  H6531   J303      1      3
...        ...    ...   ...     ...    ...    ...    ...    ...
24905588     1      3    41      12  H5019    N19      9      0
24905589     2      3    46       5   S925   R730      3      0
24905590     1      3    41      11     G_   J410     90      0
24905591     1      3    41      11   J852  J9690    101      0
24905592     1      3    41      12  H5221  H0201      0      0

[24905593 rows x 8 columns]

In [13]:
data_1920.sort_values(by=['성별코드','연령대코드'],ascending=[True,False])

          성별코드  연령대코드  시도코드  진료과목코드   주상병코드  부상병코드  입내원일수  총처방일수
2220         1     18    41       2    I652   E785      1    180
2221         1     18    41       2    I652   E785      1    180
6682         1     18    41       5  S72090   R509     45      0
6683         1     18    41       1    N201     C_     12      0
6684         1     18    41      24    K922   D509      1      0
...        ...    ...   ...     ...     ...    ...    ...    ...
24901818     2      1    26      11    G712   P942     31      0
24901820     2      1    41       4    K913   G919      9      0
24901825     2      1    27      11    P229   P023     50      0
24901826     2      1    48      11     N10   B962      5      0
24901832     2      1    11      24    S019  S0084      3      0

[24905593 rows x 8 columns]

In [ ]:
data_1920.groupby(by=['성별코드','연령대코드'])['주상병코드']

In [14]:
data_1920.sort_values(by=['성별코드','연령대코드'],ascending=[True,False])['주상병코드']

2220          I652
2221          I652
6682        S72090
6683          N201
6684          K922
             ...
24901818      G712
24901820      K913
24901825      P229
24901826       N10
24901832      S019
Name: 주상병코드, Length: 24905593, dtype: object

In [14]:
from collections import Counter

list = []

for i in range(1, 19):
    agag = data_1920['연령대코드'] == i
    aggs = data_1920[agag]
    aggs_to = Counter(aggs['주상병코드'])
    
    list.append(aggs_to.most_common(30))
    
    print('연령대코드', i, '상위 30개 질병')
    print(aggs_to.most_common(30))
    print( )
    print('-------------------------------')
    print( )

연령대코드 1 상위 30개 질병
[('J209', 453412), ('J304', 70540), ('J00', 52162), ('J029', 51109), ('J0190', 48636), ('J219', 44081), ('J0390', 39613), ('J069', 32555), ('J303', 29313), ('H66000', 28448), ('B_', 23642), ('J189', 22102), ('J0100', 20094), ('H6690', 19839), ('A090', 19426), ('J_', 19028), ('J060', 16024), ('A099', 15703), ('H6640', 13937), ('J459', 13314), ('J040', 11168), ('J329', 11113), ('R509', 9119), ('J40', 9003), ('J22', 8994), ('J320', 8862), ('J180', 8399), ('L209', 7446), ('J0180', 7001), ('L509', 6721)]

-------------------------------

연령대코드 2 상위 30개 질병
[('J209', 285705), ('J304', 59793), ('J0190', 31899), ('J029', 31073), ('J0390', 30371), ('J_', 26700), ('J303', 26278), ('J00', 24248), ('J069', 15160), ('J0100', 14833), ('J060', 14593), ('J219', 14281), ('H101', 13424), ('A090', 13415), ('J040', 12733), ('A099', 12307), ('J329', 10733), ('H66000', 10688), ('H521', 10155), ('J459', 9836), ('J189', 9803), ('F_', 9140), ('J320', 8455), ('J40', 7836), ('B_', 7421), ('H6690', 6843), ('L239', 5694), ('J22', 5694), ('J0180', 5687), ('L209', 5638)]

-------------------------------

연령대코드 3 상위 30개 질병
[('J209', 91515), ('J304', 24530), ('J0390', 15874), ('J029', 14845), ('H521', 14606), ('F_', 14424), ('J_', 14088), ('J303', 11766), ('J060', 9914), ('J0190', 9793), ('J00', 8799), ('H101', 8293), ('A099', 8125), ('A090', 7535), ('J040', 7427), ('B07', 6353), ('J069', 5391), ('L239', 5322), ('J329', 5045), ('J0100', 4990), ('E_', 4754), ('J40', 4556), ('L209', 4369), ('H5221', 4020), ('J320', 3774), ('E228', 3648), ('S9348', 3484), ('J219', 3353), ('H0001', 3107), ('H001', 3067)]

-------------------------------

연령대코드 4 상위 30개 질병
[('J209', 58184), ('F_', 25224), ('J304', 14001), ('J0390', 13834), ('J029', 12773), ('J060', 10253), ('N_', 10075), ('A099', 9534), ('J00', 8541), ('J303', 7546), ('A090', 7366), ('L239', 6796), ('J040', 6510), ('H521', 6350), ('J_', 6222), ('J0190', 5885), ('K297', 5418), ('L209', 5349), ('K291', 5305), ('J40', 5296), ('J069', 5273), ('H101', 5212), ('S3350', 5036), ('K529', 4363), ('S9348', 4087), ('J329', 3677), ('K219', 3663), ('M5456', 3659), ('S9349', 3613), ('H001', 3592)]

-------------------------------

연령대코드 5 상위 30개 질병
[('F_', 46897), ('J209', 42364), ('N_', 32992), ('J0390', 11645), ('L239', 10633), ('J304', 10063), ('J029', 9076), ('J060', 8208), ('A099', 8009), ('J00', 6645), ('B_', 6119), ('J040', 6081), ('K210', 5853), ('S3350', 5828), ('H0411', 5811), ('J303', 5740), ('H101', 5714), ('L209', 5671), ('K219', 5612), ('A090', 5547), ('A_', 5237), ('K297', 5160), ('J40', 5020), ('M5456', 4955), ('N300', 4702), ('K291', 4556), ('L238', 4401), ('M5422', 4278), ('J0190', 4180), ('J_', 4166)]

-------------------------------

연령대코드 6 상위 30개 질병
[('N_', 53674), ('F_', 49983), ('J209', 49657), ('Z_', 16670), ('J0390', 14315), ('L239', 12206), ('J304', 11832), ('J029', 10505), ('J060', 10085), ('B_', 9847), ('A099', 9628), ('K210', 8828), ('S3350', 8494), ('M5422', 8260), ('J00', 8182), ('H0411', 7625), ('A_', 7625), ('M5456', 7532), ('K219', 7404), ('J040', 7315), ('O_', 7068), ('J303', 7022), ('J40', 6657), ('K297', 6647), ('N300', 6512), ('S134', 6432), ('A090', 6343), ('H101', 6166), ('K291', 5773), ('J_', 5444)]

-------------------------------

연령대코드 7 상위 30개 질병
[('J209', 61782), ('N_', 55161), ('F_', 42333), ('Z_', 40906), ('O_', 18250), ('J0390', 15613), ('J304', 13287), ('J029', 12366), ('J060', 11420), ('L239', 10164), ('B_', 9514), ('K210', 9490), ('M5422', 9235), ('S3350', 9210), ('J00', 8945), ('J040', 8395), ('M5456', 8378), ('A099', 8069), ('J40', 7769), ('J303', 7526), ('M511', 7444), ('K219', 7373), ('S134', 6514), ('J0190', 6436), ('H0411', 6355), ('K297', 6322), ('A_', 6035), ('H101', 5603), ('N300', 5422), ('I109', 5371)]

-------------------------------

연령대코드 8 상위 30개 질병
[('J209', 90301), ('N_', 56320), ('F_', 46723), ('Z_', 30426), ('J0390', 21270), ('J304', 18612), ('I109', 17066), ('J029', 16999), ('J060', 15495), ('O_', 14631), ('K210', 13313), ('S3350', 12697), ('L239', 12155), ('B_', 12129), ('J040', 11820), ('M5456', 11814), ('M511', 11417), ('M5422', 11350), ('J00', 11293), ('J40', 10743), ('J303', 10069), ('K219', 9712), ('J0190', 9616), ('E119', 9091), ('A099', 8264), ('S134', 7918), ('K297', 7794), ('H101', 7445), ('H0411', 7404), ('J_', 7146)]

-------------------------------

연령대코드 9 상위 30개 질병
[('J209', 78969), ('N_', 51066), ('F_', 48614), ('I109', 38532), ('K210', 17802), ('J0390', 17631), ('J304', 17333), ('E119', 17140), ('M511', 14328), ('J029', 14320), ('J060', 14160), ('S3350', 13391), ('L239', 13135), ('M5456', 13017), ('B_', 12454), ('M5422', 11505), ('K219', 10885), ('J040', 10477), ('J00', 9922), ('J40', 9818), ('J303', 9531), ('M771', 9286), ('D_', 9201), ('H0411', 8883), ('N185', 8821), ('K297', 8629), ('S134', 8240), ('J0190', 7633), ('M501', 7217), ('Z_', 7169)]

-------------------------------

연령대코드 10 상위 30개 질병
[('I109', 80308), ('J209', 73719), ('N_', 53832), ('F_', 53198), ('E119', 32049), ('K210', 20572), ('M511', 17773), ('M771', 16929), ('N185', 16815), ('L239', 16248), ('J304', 16094), ('J0390', 15939), ('S3350', 15920), ('M5456', 15760), ('J029', 13518), ('B_', 13512), ('J060', 13258), ('M5422', 13249), ('K219', 12718), ('D_', 12508), ('M750', 12254), ('M751', 12072), ('M501', 11996), ('C_', 11183), ('H0411', 11082), ('J00', 10313), ('J040', 9836), ('S134', 9734), ('K297', 9600), ('J40', 9506)]

-------------------------------

연령대코드 11 상위 30개 질병
[('I109', 130126), ('J209', 67812), ('F_', 52255), ('N_', 51602), ('E119', 47820), ('K210', 24571), ('N185', 22571), ('M511', 22381), ('M750', 19390), ('L239', 18712), ('M5456', 18532), ('M771', 18139), ('M751', 17044), ('S3350', 16845), ('M501', 15253), ('J304', 14915), ('M170', 14845), ('M5422', 14767), ('K219', 14727), ('C_', 14022), ('J0390', 13772), ('B_', 13661), ('H0411', 13333), ('J029', 12743), ('J060', 12233), ('E785', 11052), ('J40', 10715), ('N300', 10622), ('B351', 10611), ('M4806', 10439)]

-------------------------------

연령대코드 12 상위 30개 질병
[('I109', 189099), ('J209', 73525), ('E119', 66715), ('F_', 56418), ('N_', 37444), ('M170', 32599), ('N185', 31974), ('K210', 28056), ('M511', 27982), ('M5456', 22983), ('L239', 20955), ('M4806', 20602), ('M751', 20282), ('M750', 20215), ('S3350', 17384), ('K219', 17291), ('M501', 16325), ('E785', 15983), ('H0411', 15462), ('J304', 14637), ('M771', 14422), ('J0390', 14157), ('M171', 13929), ('C_', 13680), ('J029', 13464), ('M5422', 13459), ('J060', 12899), ('E118', 12867), ('B_', 12274), ('B351', 12203)]

-------------------------------

연령대코드 13 상위 30개 질병
[('I109', 235201), ('E119', 77857), ('J209', 76631), ('F_', 62748), ('M170', 51882), ('M4806', 36599), ('N185', 34514), ('K210', 33447), ('M511', 31088), ('N_', 27082), ('M5456', 26544), ('M751', 22052), ('L239', 21436), ('M171', 20827), ('K219', 19521), ('M750', 19483), ('E785', 17902), ('N400', 17538), ('S3350', 17389), ('H0411', 16610), ('M501', 16400), ('E118', 15570), ('M179', 14791), ('J304', 13867), ('J40', 13626), ('J029', 12969), ('J0390', 12936), ('J060', 12623), ('C_', 12586), ('B351', 12308)]

-------------------------------

연령대코드 14 상위 30개 질병
[('I109', 214517), ('E119', 67757), ('J209', 63102), ('M170', 60053), ('F_', 56135), ('M4806', 48061), ('N185', 36391), ('M5456', 28926), ('M511', 27860), ('K210', 26186), ('M171', 23201), ('N400', 20465), ('M751', 18302), ('L239', 18092), ('M750', 17095), ('K219', 16937), ('M179', 16624), ('H0411', 14592), ('S3350', 14207), ('N_', 13917), ('E118', 13709), ('E785', 13590), ('J40', 11955), ('M501', 11674), ('J304', 11115), ('J00', 10618), ('M5422', 10493), ('K297', 10346), ('J029', 10283), ('J060', 10207)]

-------------------------------

연령대코드 15 상위 30개 질병
[('I109', 194597), ('F_', 59601), ('E119', 58231), ('M170', 56671), ('M4806', 55830), ('J209', 52696), ('N185', 39619), ('M5456', 31374), ('M511', 24575), ('N400', 24376), ('K210', 23477), ('M171', 20368), ('M179', 17011), ('L239', 16595), ('H0411', 14552), ('K219', 14253), ('E118', 13400), ('M751', 13189), ('M750', 12389), ('S3350', 11372), ('J40', 10878), ('M501', 10431), ('I639', 9919), ('J304', 9869), ('J00', 9562), ('E785', 9361), ('C_', 9326), ('I209', 9232), ('K297', 9229), ('N401', 8731)]

-------------------------------

연령대코드 16 상위 30개 질병
[('I109', 177714), ('F_', 69903), ('M4806', 62135), ('M170', 49359), ('E119', 49223), ('J209', 43879), ('M5456', 34738), ('N185', 30377), ('M511', 21907), ('N400', 21310), ('K210', 18624), ('M171', 16903), ('M179', 16654), ('L239', 14362), ('H0411', 13406), ('I639', 12286), ('K219', 11821), ('E118', 11449), ('M750', 10117), ('M4807', 9515), ('J40', 9456), ('M751', 9406), ('J00', 9232), ('M5446', 8776), ('I209', 8754), ('C_', 8607), ('S3350', 8522), ('N401', 8055), ('G20', 8006), ('J304', 7927)]

-------------------------------

연령대코드 17 상위 30개 질병
[('I109', 128016), ('F_', 70797), ('M4806', 42718), ('M170', 32286), ('E119', 29733), ('J209', 26915), ('M5456', 25448), ('N185', 22055), ('M511', 14004), ('N400', 12748), ('I639', 11557), ('M179', 11543), ('K210', 11237), ('M171', 10276), ('L239', 8537), ('H0411', 8468), ('G20', 7480), ('E118', 6830), ('M4807', 6715), ('K219', 6492), ('I209', 6422), ('J00', 6113), ('J40', 6026), ('M750', 5998), ('C_', 5655), ('N401', 5545), ('S3350', 5492), ('K297', 5400), ('J304', 5226), ('J459', 5121)]

-------------------------------

연령대코드 18 상위 30개 질병
[('F_', 81133), ('I109', 78657), ('M4806', 18887), ('M170', 15329), ('E119', 13891), ('J209', 13484), ('M5456', 12156), ('N185', 9712), ('I639', 7809), ('N400', 6340), ('M179', 5569), ('M171', 5323), ('M511', 5224), ('G20', 5107), ('L239', 4627), ('K210', 4384), ('H0411', 4343), ('I209', 3587), ('C_', 3545), ('J40', 3535), ('J189', 3492), ('E118', 3401), ('J459', 3395), ('J00', 3352), ('M750', 3303), ('K219', 3208), ('I509', 3189), ('R42', 3019), ('K297', 2932), ('N401', 2757)]

-------------------------------

In [46]:
from collections import Counter

list_d = []

for i in range(1, 19):
    agag = data_1920['연령대코드'] == i
    aggs = data_1920[agag]
    aggs_to = Counter(aggs['주상병코드'])
    
    list_d.append(aggs_to.most_common(30))
    
    print(list_d)

[[('J209', 453412), ('J304', 70540), ('J00', 52162), ('J029', 51109), ('J0190', 48636), ('J219', 44081), ('J0390', 39613), ('J069', 32555), ('J303', 29313), ('H66000', 28448), ('B_', 23642), ('J189', 22102), ('J0100', 20094), ('H6690', 19839), ('A090', 19426), ('J_', 19028), ('J060', 16024), ('A099', 15703), ('H6640', 13937), ('J459', 13314), ('J040', 11168), ('J329', 11113), ('R509', 9119), ('J40', 9003), ('J22', 8994), ('J320', 8862), ('J180', 8399), ('L209', 7446), ('J0180', 7001), ('L509', 6721)]]
[[('J209', 453412), ('J304', 70540), ('J00', 52162), ('J029', 51109), ('J0190', 48636), ('J219', 44081), ('J0390', 39613), ('J069', 32555), ('J303', 29313), ('H66000', 28448), ('B_', 23642), ('J189', 22102), ('J0100', 20094), ('H6690', 19839), ('A090', 19426), ('J_', 19028), ('J060', 16024), ('A099', 15703), ('H6640', 13937), ('J459', 13314), ('J040', 11168), ('J329', 11113), ('R509', 9119), ('J40', 9003), ('J22', 8994), ('J320', 8862), ('J180', 8399), ('L209', 7446), ('J0180', 7001), ('L509', 6721)], [('J209', 285705), ('J304', 59793), ('J0190', 31899), ('J029', 31073), ('J0390', 30371), ('J_', 26700), ('J303', 26278), ('J00', 24248), ('J069', 15160), ('J0100', 14833), ('J060', 14593), ('J219', 14281), ('H101', 13424), ('A090', 13415), ('J040', 12733), ('A099', 12307), ('J329', 10733), ('H66000', 10688), ('H521', 10155), ('J459', 9836), ('J189', 9803), ('F_', 9140), ('J320', 8455), ('J40', 7836), ('B_', 7421), ('H6690', 6843), ('L239', 5694), ('J22', 5694), ('J0180', 5687), ('L209', 5638)]]
[[('J209', 453412), ('J304', 70540), ('J00', 52162), ('J029', 51109), ('J0190', 48636), ('J219', 44081), ('J0390', 39613), ('J069', 32555), ('J303', 29313), ('H66000', 28448), ('B_', 23642), ('J189', 22102), ('J0100', 20094), ('H6690', 19839), ('A090', 19426), ('J_', 19028), ('J060', 16024), ('A099', 15703), ('H6640', 13937), ('J459', 13314), ('J040', 11168), ('J329', 11113), ('R509', 9119), ('J40', 9003), ('J22', 8994), ('J320', 8862), ('J180', 8399), ('L209', 7446), ('J0180', 7001), ('L509', 6721)], [('J209', 285705), ('J304', 59793), ('J0190', 31899), ('J029', 31073), ('J0390', 30371), ('J_', 26700), ('J303', 26278), ('J00', 24248), ('J069', 15160), ('J0100', 14833), ('J060', 14593), ('J219', 14281), ('H101', 13424), ('A090', 13415), ('J040', 12733), ('A099', 12307), ('J329', 10733), ('H66000', 10688), ('H521', 10155), ('J459', 9836), ('J189', 9803), ('F_', 9140), ('J320', 8455), ('J40', 7836), ('B_', 7421), ('H6690', 6843), ('L239', 5694), ('J22', 5694), ('J0180', 5687), ('L209', 5638)], [('J209', 91515), ('J304', 24530), ('J0390', 15874), ('J029', 14845), ('H521', 14606), ('F_', 14424), ('J_', 14088), ('J303', 11766), ('J060', 9914), ('J0190', 9793), ('J00', 8799), ('H101', 8293), ('A099', 8125), ('A090', 7535), ('J040', 7427), ('B07', 6353), ('J069', 5391), ('L239', 5322), ('J329', 5045), ('J0100', 4990), ('E_', 4754), ('J40', 4556), ('L209', 4369), ('H5221', 4020), ('J320', 3774), ('E228', 3648), ('S9348', 3484), ('J219', 3353), ('H0001', 3107), ('H001', 3067)]]
[[('J209', 453412), ('J304', 70540), ('J00', 52162), ('J029', 51109), ('J0190', 48636), ('J219', 44081), ('J0390', 39613), ('J069', 32555), ('J303', 29313), ('H66000', 28448), ('B_', 23642), ('J189', 22102), ('J0100', 20094), ('H6690', 19839), ('A090', 19426), ('J_', 19028), ('J060', 16024), ('A099', 15703), ('H6640', 13937), ('J459', 13314), ('J040', 11168), ('J329', 11113), ('R509', 9119), ('J40', 9003), ('J22', 8994), ('J320', 8862), ('J180', 8399), ('L209', 7446), ('J0180', 7001), ('L509', 6721)], [('J209', 285705), ('J304', 59793), ('J0190', 31899), ('J029', 31073), ('J0390', 30371), ('J_', 26700), ('J303', 26278), ('J00', 24248), ('J069', 15160), ('J0100', 14833), ('J060', 14593), ('J219', 14281), ('H101', 13424), ('A090', 13415), ('J040', 12733), ('A099', 12307), ('J329', 10733), ('H66000', 10688), ('H521', 10155), ('J459', 9836), ('J189', 9803), ('F_', 9140), ('J320', 8455), ('J40', 7836), ('B_', 7421), ('H6690', 6843), ('L239', 5694), ('J22', 5694), ('J0180', 5687), ('L209', 5638)], [('J209', 91515), ('J304', 24530), ('J0390', 15874), ('J029', 14845), ('H521', 14606), ('F_', 14424), ('J_', 14088), ('J303', 11766), ('J060', 9914), ('J0190', 9793), ('J00', 8799), ('H101', 8293), ('A099', 8125), ('A090', 7535), ('J040', 7427), ('B07', 6353), ('J069', 5391), ('L239', 5322), ('J329', 5045), ('J0100', 4990), ('E_', 4754), ('J40', 4556), ('L209', 4369), ('H5221', 4020), ('J320', 3774), ('E228', 3648), ('S9348', 3484), ('J219', 3353), ('H0001', 3107), ('H001', 3067)], [('J209', 58184), ('F_', 25224), ('J304', 14001), ('J0390', 13834), ('J029', 12773), ('J060', 10253), ('N_', 10075), ('A099', 9534), ('J00', 8541), ('J303', 7546), ('A090', 7366), ('L239', 6796), ('J040', 6510), ('H521', 6350), ('J_', 6222), ('J0190', 5885), ('K297', 5418), ('L209', 5349), ('K291', 5305), ('J40', 5296), ('J069', 5273), ('H101', 5212), ('S3350', 5036), ('K529', 4363), ('S9348', 4087), ('J329', 3677), ('K219', 3663), ('M5456', 3659), ('S9349', 3613), ('H001', 3592)]]
[[('J209', 453412), ('J304', 70540), ('J00', 52162), ('J029', 51109), ('J0190', 48636), ('J219', 44081), ('J0390', 39613), ('J069', 32555), ('J303', 29313), ('H66000', 28448), ('B_', 23642), ('J189', 22102), ('J0100', 20094), ('H6690', 19839), ('A090', 19426), ('J_', 19028), ('J060', 16024), ('A099', 15703), ('H6640', 13937), ('J459', 13314), ('J040', 11168), ('J329', 11113), ('R509', 9119), ('J40', 9003), ('J22', 8994), ('J320', 8862), ('J180', 8399), ('L209', 7446), ('J0180', 7001), ('L509', 6721)], [('J209', 285705), ('J304', 59793), ('J0190', 31899), ('J029', 31073), ('J0390', 30371), ('J_', 26700), ('J303', 26278), ('J00', 24248), ('J069', 15160), ('J0100', 14833), ('J060', 14593), ('J219', 14281), ('H101', 13424), ('A090', 13415), ('J040', 12733), ('A099', 12307), ('J329', 10733), ('H66000', 10688), ('H521', 10155), ('J459', 9836), ('J189', 9803), ('F_', 9140), ('J320', 8455), ('J40', 7836), ('B_', 7421), ('H6690', 6843), ('L239', 5694), ('J22', 5694), ('J0180', 5687), ('L209', 5638)], [('J209', 91515), ('J304', 24530), ('J0390', 15874), ('J029', 14845), ('H521', 14606), ('F_', 14424), ('J_', 14088), ('J303', 11766), ('J060', 9914), ('J0190', 9793), ('J00', 8799), ('H101', 8293), ('A099', 8125), ('A090', 7535), ('J040', 7427), ('B07', 6353), ('J069', 5391), ('L239', 5322), ('J329', 5045), ('J0100', 4990), ('E_', 4754), ('J40', 4556), ('L209', 4369), ('H5221', 4020), ('J320', 3774), ('E228', 3648), ('S9348', 3484), ('J219', 3353), ('H0001', 3107), ('H001', 3067)], [('J209', 58184), ('F_', 25224), ('J304', 14001), ('J0390', 13834), ('J029', 12773), ('J060', 10253), ('N_', 10075), ('A099', 9534), ('J00', 8541), ('J303', 7546), ('A090', 7366), ('L239', 6796), ('J040', 6510), ('H521', 6350), ('J_', 6222), ('J0190', 5885), ('K297', 5418), ('L209', 5349), ('K291', 5305), ('J40', 5296), ('J069', 5273), ('H101', 5212), ('S3350', 5036), ('K529', 4363), ('S9348', 4087), ('J329', 3677), ('K219', 3663), ('M5456', 3659), ('S9349', 3613), ('H001', 3592)], [('F_', 46897), ('J209', 42364), ('N_', 32992), ('J0390', 11645), ('L239', 10633), ('J304', 10063), ('J029', 9076), ('J060', 8208), ('A099', 8009), ('J00', 6645), ('B_', 6119), ('J040', 6081), ('K210', 5853), ('S3350', 5828), ('H0411', 5811), ('J303', 5740), ('H101', 5714), ('L209', 5671), ('K219', 5612), ('A090', 5547), ('A_', 5237), ('K297', 5160), ('J40', 5020), ('M5456', 4955), ('N300', 4702), ('K291', 4556), ('L238', 4401), ('M5422', 4278), ('J0190', 4180), ('J_', 4166)]]
[[('J209', 453412), ('J304', 70540), ('J00', 52162), ('J029', 51109), ('J0190', 48636), ('J219', 44081), ('J0390', 39613), ('J069', 32555), ('J303', 29313), ('H66000', 28448), ('B_', 23642), ('J189', 22102), ('J0100', 20094), ('H6690', 19839), ('A090', 19426), ('J_', 19028), ('J060', 16024), ('A099', 15703), ('H6640', 13937), ('J459', 13314), ('J040', 11168), ('J329', 11113), ('R509', 9119), ('J40', 9003), ('J22', 8994), ('J320', 8862), ('J180', 8399), ('L209', 7446), ('J0180', 7001), ('L509', 6721)], [('J209', 285705), ('J304', 59793), ('J0190', 31899), ('J029', 31073), ('J0390', 30371), ('J_', 26700), ('J303', 26278), ('J00', 24248), ('J069', 15160), ('J0100', 14833), ('J060', 14593), ('J219', 14281), ('H101', 13424), ('A090', 13415), ('J040', 12733), ('A099', 12307), ('J329', 10733), ('H66000', 10688), ('H521', 10155), ('J459', 9836), ('J189', 9803), ('F_', 9140), ('J320', 8455), ('J40', 7836), ('B_', 7421), ('H6690', 6843), ('L239', 5694), ('J22', 5694), ('J0180', 5687), ('L209', 5638)], [('J209', 91515), ('J304', 24530), ('J0390', 15874), ('J029', 14845), ('H521', 14606), ('F_', 14424), ('J_', 14088), ('J303', 11766), ('J060', 9914), ('J0190', 9793), ('J00', 8799), ('H101', 8293), ('A099', 8125), ('A090', 7535), ('J040', 7427), ('B07', 6353), ('J069', 5391), ('L239', 5322), ('J329', 5045), ('J0100', 4990), ('E_', 4754), ('J40', 4556), ('L209', 4369), ('H5221', 4020), ('J320', 3774), ('E228', 3648), ('S9348', 3484), ('J219', 3353), ('H0001', 3107), ('H001', 3067)], [('J209', 58184), ('F_', 25224), ('J304', 14001), ('J0390', 13834), ('J029', 12773), ('J060', 10253), ('N_', 10075), ('A099', 9534), ('J00', 8541), ('J303', 7546), ('A090', 7366), ('L239', 6796), ('J040', 6510), ('H521', 6350), ('J_', 6222), ('J0190', 5885), ('K297', 5418), ('L209', 5349), ('K291', 5305), ('J40', 5296), ('J069', 5273), ('H101', 5212), ('S3350', 5036), ('K529', 4363), ('S9348', 4087), ('J329', 3677), ('K219', 3663), ('M5456', 3659), ('S9349', 3613), ('H001', 3592)], [('F_', 46897), ('J209', 42364), ('N_', 32992), ('J0390', 11645), ('L239', 10633), ('J304', 10063), ('J029', 9076), ('J060', 8208), ('A099', 8009), ('J00', 6645), ('B_', 6119), ('J040', 6081), ('K210', 5853), ('S3350', 5828), ('H0411', 5811), ('J303', 5740), ('H101', 5714), ('L209', 5671), ('K219', 5612), ('A090', 5547), ('A_', 5237), ('K297', 5160), ('J40', 5020), ('M5456', 4955), ('N300', 4702), ('K291', 4556), ('L238', 4401), ('M5422', 4278), ('J0190', 4180), ('J_', 4166)], [('N_', 53674), ('F_', 49983), ('J209', 49657), ('Z_', 16670), ('J0390', 14315), ('L239', 12206), ('J304', 11832), ('J029', 10505), ('J060', 10085), ('B_', 9847), ('A099', 9628), ('K210', 8828), ('S3350', 8494), ('M5422', 8260), ('J00', 8182), ('H0411', 7625), ('A_', 7625), ('M5456', 7532), ('K219', 7404), ('J040', 7315), ('O_', 7068), ('J303', 7022), ('J40', 6657), ('K297', 6647), ('N300', 6512), ('S134', 6432), ('A090', 6343), ('H101', 6166), ('K291', 5773), ('J_', 5444)]]

[[('J209', 453412), ('J304', 70540), ('J00', 52162), ('J029', 51109), ('J0190', 48636), ('J219', 44081), ('J0390', 39613), ('J069', 32555), ('J303', 29313), ('H66000', 28448), ('B_', 23642), ('J189', 22102), ('J0100', 20094), ('H6690', 19839), ('A090', 19426), ('J_', 19028), ('J060', 16024), ('A099', 15703), ('H6640', 13937), ('J459', 13314), ('J040', 11168), ('J329', 11113), ('R509', 9119), ('J40', 9003), ('J22', 8994), ('J320', 8862), ('J180', 8399), ('L209', 7446), ('J0180', 7001), ('L509', 6721)], [('J209', 285705), ('J304', 59793), ('J0190', 31899), ('J029', 31073), ('J0390', 30371), ('J_', 26700), ('J303', 26278), ('J00', 24248), ('J069', 15160), ('J0100', 14833), ('J060', 14593), ('J219', 14281), ('H101', 13424), ('A090', 13415), ('J040', 12733), ('A099', 12307), ('J329', 10733), ('H66000', 10688), ('H521', 10155), ('J459', 9836), ('J189', 9803), ('F_', 9140), ('J320', 8455), ('J40', 7836), ('B_', 7421), ('H6690', 6843), ('L239', 5694), ('J22', 5694), ('J0180', 5687), ('L209', 5638)], [('J209', 91515), ('J304', 24530), ('J0390', 15874), ('J029', 14845), ('H521', 14606), ('F_', 14424), ('J_', 14088), ('J303', 11766), ('J060', 9914), ('J0190', 9793), ('J00', 8799), ('H101', 8293), ('A099', 8125), ('A090', 7535), ('J040', 7427), ('B07', 6353), ('J069', 5391), ('L239', 5322), ('J329', 5045), ('J0100', 4990), ('E_', 4754), ('J40', 4556), ('L209', 4369), ('H5221', 4020), ('J320', 3774), ('E228', 3648), ('S9348', 3484), ('J219', 3353), ('H0001', 3107), ('H001', 3067)], [('J209', 58184), ('F_', 25224), ('J304', 14001), ('J0390', 13834), ('J029', 12773), ('J060', 10253), ('N_', 10075), ('A099', 9534), ('J00', 8541), ('J303', 7546), ('A090', 7366), ('L239', 6796), ('J040', 6510), ('H521', 6350), ('J_', 6222), ('J0190', 5885), ('K297', 5418), ('L209', 5349), ('K291', 5305), ('J40', 5296), ('J069', 5273), ('H101', 5212), ('S3350', 5036), ('K529', 4363), ('S9348', 4087), ('J329', 3677), ('K219', 3663), ('M5456', 3659), ('S9349', 3613), ('H001', 3592)], [('F_', 46897), ('J209', 42364), ('N_', 32992), ('J0390', 11645), ('L239', 10633), ('J304', 10063), ('J029', 9076), ('J060', 8208), ('A099', 8009), ('J00', 6645), ('B_', 6119), ('J040', 6081), ('K210', 5853), ('S3350', 5828), ('H0411', 5811), ('J303', 5740), ('H101', 5714), ('L209', 5671), ('K219', 5612), ('A090', 5547), ('A_', 5237), ('K297', 5160), ('J40', 5020), ('M5456', 4955), ('N300', 4702), ('K291', 4556), ('L238', 4401), ('M5422', 4278), ('J0190', 4180), ('J_', 4166)], [('N_', 53674), ('F_', 49983), ('J209', 49657), ('Z_', 16670), ('J0390', 14315), ('L239', 12206), ('J304', 11832), ('J029', 10505), ('J060', 10085), ('B_', 9847), ('A099', 9628), ('K210', 8828), ('S3350', 8494), ('M5422', 8260), ('J00', 8182), ('H0411', 7625), ('A_', 7625), ('M5456', 7532), ('K219', 7404), ('J040', 7315), ('O_', 7068), ('J303', 7022), ('J40', 6657), ('K297', 6647), ('N300', 6512), ('S134', 6432), ('A090', 6343), ('H101', 6166), ('K291', 5773), ('J_', 5444)], [('J209', 61782), ('N_', 55161), ('F_', 42333), ('Z_', 40906), ('O_', 18250), ('J0390', 15613), ('J304', 13287), ('J029', 12366), ('J060', 11420), ('L239', 10164), ('B_', 9514), ('K210', 9490), ('M5422', 9235), ('S3350', 9210), ('J00', 8945), ('J040', 8395), ('M5456', 8378), ('A099', 8069), ('J40', 7769), ('J303', 7526), ('M511', 7444), ('K219', 7373), ('S134', 6514), ('J0190', 6436), ('H0411', 6355), ('K297', 6322), ('A_', 6035), ('H101', 5603), ('N300', 5422), ('I109', 5371)]]
[[('J209', 453412), ('J304', 70540), ('J00', 52162), ('J029', 51109), ('J0190', 48636), ('J219', 44081), ('J0390', 39613), ('J069', 32555), ('J303', 29313), ('H66000', 28448), ('B_', 23642), ('J189', 22102), ('J0100', 20094), ('H6690', 19839), ('A090', 19426), ('J_', 19028), ('J060', 16024), ('A099', 15703), ('H6640', 13937), ('J459', 13314), ('J040', 11168), ('J329', 11113), ('R509', 9119), ('J40', 9003), ('J22', 8994), ('J320', 8862), ('J180', 8399), ('L209', 7446), ('J0180', 7001), ('L509', 6721)], [('J209', 285705), ('J304', 59793), ('J0190', 31899), ('J029', 31073), ('J0390', 30371), ('J_', 26700), ('J303', 26278), ('J00', 24248), ('J069', 15160), ('J0100', 14833), ('J060', 14593), ('J219', 14281), ('H101', 13424), ('A090', 13415), ('J040', 12733), ('A099', 12307), ('J329', 10733), ('H66000', 10688), ('H521', 10155), ('J459', 9836), ('J189', 9803), ('F_', 9140), ('J320', 8455), ('J40', 7836), ('B_', 7421), ('H6690', 6843), ('L239', 5694), ('J22', 5694), ('J0180', 5687), ('L209', 5638)], [('J209', 91515), ('J304', 24530), ('J0390', 15874), ('J029', 14845), ('H521', 14606), ('F_', 14424), ('J_', 14088), ('J303', 11766), ('J060', 9914), ('J0190', 9793), ('J00', 8799), ('H101', 8293), ('A099', 8125), ('A090', 7535), ('J040', 7427), ('B07', 6353), ('J069', 5391), ('L239', 5322), ('J329', 5045), ('J0100', 4990), ('E_', 4754), ('J40', 4556), ('L209', 4369), ('H5221', 4020), ('J320', 3774), ('E228', 3648), ('S9348', 3484), ('J219', 3353), ('H0001', 3107), ('H001', 3067)], [('J209', 58184), ('F_', 25224), ('J304', 14001), ('J0390', 13834), ('J029', 12773), ('J060', 10253), ('N_', 10075), ('A099', 9534), ('J00', 8541), ('J303', 7546), ('A090', 7366), ('L239', 6796), ('J040', 6510), ('H521', 6350), ('J_', 6222), ('J0190', 5885), ('K297', 5418), ('L209', 5349), ('K291', 5305), ('J40', 5296), ('J069', 5273), ('H101', 5212), ('S3350', 5036), ('K529', 4363), ('S9348', 4087), ('J329', 3677), ('K219', 3663), ('M5456', 3659), ('S9349', 3613), ('H001', 3592)], [('F_', 46897), ('J209', 42364), ('N_', 32992), ('J0390', 11645), ('L239', 10633), ('J304', 10063), ('J029', 9076), ('J060', 8208), ('A099', 8009), ('J00', 6645), ('B_', 6119), ('J040', 6081), ('K210', 5853), ('S3350', 5828), ('H0411', 5811), ('J303', 5740), ('H101', 5714), ('L209', 5671), ('K219', 5612), ('A090', 5547), ('A_', 5237), ('K297', 5160), ('J40', 5020), ('M5456', 4955), ('N300', 4702), ('K291', 4556), ('L238', 4401), ('M5422', 4278), ('J0190', 4180), ('J_', 4166)], [('N_', 53674), ('F_', 49983), ('J209', 49657), ('Z_', 16670), ('J0390', 14315), ('L239', 12206), ('J304', 11832), ('J029', 10505), ('J060', 10085), ('B_', 9847), ('A099', 9628), ('K210', 8828), ('S3350', 8494), ('M5422', 8260), ('J00', 8182), ('H0411', 7625), ('A_', 7625), ('M5456', 7532), ('K219', 7404), ('J040', 7315), ('O_', 7068), ('J303', 7022), ('J40', 6657), ('K297', 6647), ('N300', 6512), ('S134', 6432), ('A090', 6343), ('H101', 6166), ('K291', 5773), ('J_', 5444)], [('J209', 61782), ('N_', 55161), ('F_', 42333), ('Z_', 40906), ('O_', 18250), ('J0390', 15613), ('J304', 13287), ('J029', 12366), ('J060', 11420), ('L239', 10164), ('B_', 9514), ('K210', 9490), ('M5422', 9235), ('S3350', 9210), ('J00', 8945), ('J040', 8395), ('M5456', 8378), ('A099', 8069), ('J40', 7769), ('J303', 7526), ('M511', 7444), ('K219', 7373), ('S134', 6514), ('J0190', 6436), ('H0411', 6355), ('K297', 6322), ('A_', 6035), ('H101', 5603), ('N300', 5422), ('I109', 5371)], [('J209', 90301), ('N_', 56320), ('F_', 46723), ('Z_', 30426), ('J0390', 21270), ('J304', 18612), ('I109', 17066), ('J029', 16999), ('J060', 15495), ('O_', 14631), ('K210', 13313), ('S3350', 12697), ('L239', 12155), ('B_', 12129), ('J040', 11820), ('M5456', 11814), ('M511', 11417), ('M5422', 11350), ('J00', 11293), ('J40', 10743), ('J303', 10069), ('K219', 9712), ('J0190', 9616), ('E119', 9091), ('A099', 8264), ('S134', 7918), ('K297', 7794), ('H101', 7445), ('H0411', 7404), ('J_', 7146)]]
[[('J209', 453412), ('J304', 70540), ('J00', 52162), ('J029', 51109), ('J0190', 48636), ('J219', 44081), ('J0390', 39613), ('J069', 32555), ('J303', 29313), ('H66000', 28448), ('B_', 23642), ('J189', 22102), ('J0100', 20094), ('H6690', 19839), ('A090', 19426), ('J_', 19028), ('J060', 16024), ('A099', 15703), ('H6640', 13937), ('J459', 13314), ('J040', 11168), ('J329', 11113), ('R509', 9119), ('J40', 9003), ('J22', 8994), ('J320', 8862), ('J180', 8399), ('L209', 7446), ('J0180', 7001), ('L509', 6721)], [('J209', 285705), ('J304', 59793), ('J0190', 31899), ('J029', 31073), ('J0390', 30371), ('J_', 26700), ('J303', 26278), ('J00', 24248), ('J069', 15160), ('J0100', 14833), ('J060', 14593), ('J219', 14281), ('H101', 13424), ('A090', 13415), ('J040', 12733), ('A099', 12307), ('J329', 10733), ('H66000', 10688), ('H521', 10155), ('J459', 9836), ('J189', 9803), ('F_', 9140), ('J320', 8455), ('J40', 7836), ('B_', 7421), ('H6690', 6843), ('L239', 5694), ('J22', 5694), ('J0180', 5687), ('L209', 5638)], [('J209', 91515), ('J304', 24530), ('J0390', 15874), ('J029', 14845), ('H521', 14606), ('F_', 14424), ('J_', 14088), ('J303', 11766), ('J060', 9914), ('J0190', 9793), ('J00', 8799), ('H101', 8293), ('A099', 8125), ('A090', 7535), ('J040', 7427), ('B07', 6353), ('J069', 5391), ('L239', 5322), ('J329', 5045), ('J0100', 4990), ('E_', 4754), ('J40', 4556), ('L209', 4369), ('H5221', 4020), ('J320', 3774), ('E228', 3648), ('S9348', 3484), ('J219', 3353), ('H0001', 3107), ('H001', 3067)], [('J209', 58184), ('F_', 25224), ('J304', 14001), ('J0390', 13834), ('J029', 12773), ('J060', 10253), ('N_', 10075), ('A099', 9534), ('J00', 8541), ('J303', 7546), ('A090', 7366), ('L239', 6796), ('J040', 6510), ('H521', 6350), ('J_', 6222), ('J0190', 5885), ('K297', 5418), ('L209', 5349), ('K291', 5305), ('J40', 5296), ('J069', 5273), ('H101', 5212), ('S3350', 5036), ('K529', 4363), ('S9348', 4087), ('J329', 3677), ('K219', 3663), ('M5456', 3659), ('S9349', 3613), ('H001', 3592)], [('F_', 46897), ('J209', 42364), ('N_', 32992), ('J0390', 11645), ('L239', 10633), ('J304', 10063), ('J029', 9076), ('J060', 8208), ('A099', 8009), ('J00', 6645), ('B_', 6119), ('J040', 6081), ('K210', 5853), ('S3350', 5828), ('H0411', 5811), ('J303', 5740), ('H101', 5714), ('L209', 5671), ('K219', 5612), ('A090', 5547), ('A_', 5237), ('K297', 5160), ('J40', 5020), ('M5456', 4955), ('N300', 4702), ('K291', 4556), ('L238', 4401), ('M5422', 4278), ('J0190', 4180), ('J_', 4166)], [('N_', 53674), ('F_', 49983), ('J209', 49657), ('Z_', 16670), ('J0390', 14315), ('L239', 12206), ('J304', 11832), ('J029', 10505), ('J060', 10085), ('B_', 9847), ('A099', 9628), ('K210', 8828), ('S3350', 8494), ('M5422', 8260), ('J00', 8182), ('H0411', 7625), ('A_', 7625), ('M5456', 7532), ('K219', 7404), ('J040', 7315), ('O_', 7068), ('J303', 7022), ('J40', 6657), ('K297', 6647), ('N300', 6512), ('S134', 6432), ('A090', 6343), ('H101', 6166), ('K291', 5773), ('J_', 5444)], [('J209', 61782), ('N_', 55161), ('F_', 42333), ('Z_', 40906), ('O_', 18250), ('J0390', 15613), ('J304', 13287), ('J029', 12366), ('J060', 11420), ('L239', 10164), ('B_', 9514), ('K210', 9490), ('M5422', 9235), ('S3350', 9210), ('J00', 8945), ('J040', 8395), ('M5456', 8378), ('A099', 8069), ('J40', 7769), ('J303', 7526), ('M511', 7444), ('K219', 7373), ('S134', 6514), ('J0190', 6436), ('H0411', 6355), ('K297', 6322), ('A_', 6035), ('H101', 5603), ('N300', 5422), ('I109', 5371)], [('J209', 90301), ('N_', 56320), ('F_', 46723), ('Z_', 30426), ('J0390', 21270), ('J304', 18612), ('I109', 17066), ('J029', 16999), ('J060', 15495), ('O_', 14631), ('K210', 13313), ('S3350', 12697), ('L239', 12155), ('B_', 12129), ('J040', 11820), ('M5456', 11814), ('M511', 11417), ('M5422', 11350), ('J00', 11293), ('J40', 10743), ('J303', 10069), ('K219', 9712), ('J0190', 9616), ('E119', 9091), ('A099', 8264), ('S134', 7918), ('K297', 7794), ('H101', 7445), ('H0411', 7404), ('J_', 7146)], [('J209', 78969), ('N_', 51066), ('F_', 48614), ('I109', 38532), ('K210', 17802), ('J0390', 17631), ('J304', 17333), ('E119', 17140), ('M511', 14328), ('J029', 14320), ('J060', 14160), ('S3350', 13391), ('L239', 13135), ('M5456', 13017), ('B_', 12454), ('M5422', 11505), ('K219', 10885), ('J040', 10477), ('J00', 9922), ('J40', 9818), ('J303', 9531), ('M771', 9286), ('D_', 9201), ('H0411', 8883), ('N185', 8821), ('K297', 8629), ('S134', 8240), ('J0190', 7633), ('M501', 7217), ('Z_', 7169)]]

[[('J209', 453412), ('J304', 70540), ('J00', 52162), ('J029', 51109), ('J0190', 48636), ('J219', 44081), ('J0390', 39613), ('J069', 32555), ('J303', 29313), ('H66000', 28448), ('B_', 23642), ('J189', 22102), ('J0100', 20094), ('H6690', 19839), ('A090', 19426), ('J_', 19028), ('J060', 16024), ('A099', 15703), ('H6640', 13937), ('J459', 13314), ('J040', 11168), ('J329', 11113), ('R509', 9119), ('J40', 9003), ('J22', 8994), ('J320', 8862), ('J180', 8399), ('L209', 7446), ('J0180', 7001), ('L509', 6721)], [('J209', 285705), ('J304', 59793), ('J0190', 31899), ('J029', 31073), ('J0390', 30371), ('J_', 26700), ('J303', 26278), ('J00', 24248), ('J069', 15160), ('J0100', 14833), ('J060', 14593), ('J219', 14281), ('H101', 13424), ('A090', 13415), ('J040', 12733), ('A099', 12307), ('J329', 10733), ('H66000', 10688), ('H521', 10155), ('J459', 9836), ('J189', 9803), ('F_', 9140), ('J320', 8455), ('J40', 7836), ('B_', 7421), ('H6690', 6843), ('L239', 5694), ('J22', 5694), ('J0180', 5687), ('L209', 5638)], [('J209', 91515), ('J304', 24530), ('J0390', 15874), ('J029', 14845), ('H521', 14606), ('F_', 14424), ('J_', 14088), ('J303', 11766), ('J060', 9914), ('J0190', 9793), ('J00', 8799), ('H101', 8293), ('A099', 8125), ('A090', 7535), ('J040', 7427), ('B07', 6353), ('J069', 5391), ('L239', 5322), ('J329', 5045), ('J0100', 4990), ('E_', 4754), ('J40', 4556), ('L209', 4369), ('H5221', 4020), ('J320', 3774), ('E228', 3648), ('S9348', 3484), ('J219', 3353), ('H0001', 3107), ('H001', 3067)], [('J209', 58184), ('F_', 25224), ('J304', 14001), ('J0390', 13834), ('J029', 12773), ('J060', 10253), ('N_', 10075), ('A099', 9534), ('J00', 8541), ('J303', 7546), ('A090', 7366), ('L239', 6796), ('J040', 6510), ('H521', 6350), ('J_', 6222), ('J0190', 5885), ('K297', 5418), ('L209', 5349), ('K291', 5305), ('J40', 5296), ('J069', 5273), ('H101', 5212), ('S3350', 5036), ('K529', 4363), ('S9348', 4087), ('J329', 3677), ('K219', 3663), ('M5456', 3659), ('S9349', 3613), ('H001', 3592)], [('F_', 46897), ('J209', 42364), ('N_', 32992), ('J0390', 11645), ('L239', 10633), ('J304', 10063), ('J029', 9076), ('J060', 8208), ('A099', 8009), ('J00', 6645), ('B_', 6119), ('J040', 6081), ('K210', 5853), ('S3350', 5828), ('H0411', 5811), ('J303', 5740), ('H101', 5714), ('L209', 5671), ('K219', 5612), ('A090', 5547), ('A_', 5237), ('K297', 5160), ('J40', 5020), ('M5456', 4955), ('N300', 4702), ('K291', 4556), ('L238', 4401), ('M5422', 4278), ('J0190', 4180), ('J_', 4166)], [('N_', 53674), ('F_', 49983), ('J209', 49657), ('Z_', 16670), ('J0390', 14315), ('L239', 12206), ('J304', 11832), ('J029', 10505), ('J060', 10085), ('B_', 9847), ('A099', 9628), ('K210', 8828), ('S3350', 8494), ('M5422', 8260), ('J00', 8182), ('H0411', 7625), ('A_', 7625), ('M5456', 7532), ('K219', 7404), ('J040', 7315), ('O_', 7068), ('J303', 7022), ('J40', 6657), ('K297', 6647), ('N300', 6512), ('S134', 6432), ('A090', 6343), ('H101', 6166), ('K291', 5773), ('J_', 5444)], [('J209', 61782), ('N_', 55161), ('F_', 42333), ('Z_', 40906), ('O_', 18250), ('J0390', 15613), ('J304', 13287), ('J029', 12366), ('J060', 11420), ('L239', 10164), ('B_', 9514), ('K210', 9490), ('M5422', 9235), ('S3350', 9210), ('J00', 8945), ('J040', 8395), ('M5456', 8378), ('A099', 8069), ('J40', 7769), ('J303', 7526), ('M511', 7444), ('K219', 7373), ('S134', 6514), ('J0190', 6436), ('H0411', 6355), ('K297', 6322), ('A_', 6035), ('H101', 5603), ('N300', 5422), ('I109', 5371)], [('J209', 90301), ('N_', 56320), ('F_', 46723), ('Z_', 30426), ('J0390', 21270), ('J304', 18612), ('I109', 17066), ('J029', 16999), ('J060', 15495), ('O_', 14631), ('K210', 13313), ('S3350', 12697), ('L239', 12155), ('B_', 12129), ('J040', 11820), ('M5456', 11814), ('M511', 11417), ('M5422', 11350), ('J00', 11293), ('J40', 10743), ('J303', 10069), ('K219', 9712), ('J0190', 9616), ('E119', 9091), ('A099', 8264), ('S134', 7918), ('K297', 7794), ('H101', 7445), ('H0411', 7404), ('J_', 7146)], [('J209', 78969), ('N_', 51066), ('F_', 48614), ('I109', 38532), ('K210', 17802), ('J0390', 17631), ('J304', 17333), ('E119', 17140), ('M511', 14328), ('J029', 14320), ('J060', 14160), ('S3350', 13391), ('L239', 13135), ('M5456', 13017), ('B_', 12454), ('M5422', 11505), ('K219', 10885), ('J040', 10477), ('J00', 9922), ('J40', 9818), ('J303', 9531), ('M771', 9286), ('D_', 9201), ('H0411', 8883), ('N185', 8821), ('K297', 8629), ('S134', 8240), ('J0190', 7633), ('M501', 7217), ('Z_', 7169)], [('I109', 80308), ('J209', 73719), ('N_', 53832), ('F_', 53198), ('E119', 32049), ('K210', 20572), ('M511', 17773), ('M771', 16929), ('N185', 16815), ('L239', 16248), ('J304', 16094), ('J0390', 15939), ('S3350', 15920), ('M5456', 15760), ('J029', 13518), ('B_', 13512), ('J060', 13258), ('M5422', 13249), ('K219', 12718), ('D_', 12508), ('M750', 12254), ('M751', 12072), ('M501', 11996), ('C_', 11183), ('H0411', 11082), ('J00', 10313), ('J040', 9836), ('S134', 9734), ('K297', 9600), ('J40', 9506)]]
[[('J209', 453412), ('J304', 70540), ('J00', 52162), ('J029', 51109), ('J0190', 48636), ('J219', 44081), ('J0390', 39613), ('J069', 32555), ('J303', 29313), ('H66000', 28448), ('B_', 23642), ('J189', 22102), ('J0100', 20094), ('H6690', 19839), ('A090', 19426), ('J_', 19028), ('J060', 16024), ('A099', 15703), ('H6640', 13937), ('J459', 13314), ('J040', 11168), ('J329', 11113), ('R509', 9119), ('J40', 9003), ('J22', 8994), ('J320', 8862), ('J180', 8399), ('L209', 7446), ('J0180', 7001), ('L509', 6721)], [('J209', 285705), ('J304', 59793), ('J0190', 31899), ('J029', 31073), ('J0390', 30371), ('J_', 26700), ('J303', 26278), ('J00', 24248), ('J069', 15160), ('J0100', 14833), ('J060', 14593), ('J219', 14281), ('H101', 13424), ('A090', 13415), ('J040', 12733), ('A099', 12307), ('J329', 10733), ('H66000', 10688), ('H521', 10155), ('J459', 9836), ('J189', 9803), ('F_', 9140), ('J320', 8455), ('J40', 7836), ('B_', 7421), ('H6690', 6843), ('L239', 5694), ('J22', 5694), ('J0180', 5687), ('L209', 5638)], [('J209', 91515), ('J304', 24530), ('J0390', 15874), ('J029', 14845), ('H521', 14606), ('F_', 14424), ('J_', 14088), ('J303', 11766), ('J060', 9914), ('J0190', 9793), ('J00', 8799), ('H101', 8293), ('A099', 8125), ('A090', 7535), ('J040', 7427), ('B07', 6353), ('J069', 5391), ('L239', 5322), ('J329', 5045), ('J0100', 4990), ('E_', 4754), ('J40', 4556), ('L209', 4369), ('H5221', 4020), ('J320', 3774), ('E228', 3648), ('S9348', 3484), ('J219', 3353), ('H0001', 3107), ('H001', 3067)], [('J209', 58184), ('F_', 25224), ('J304', 14001), ('J0390', 13834), ('J029', 12773), ('J060', 10253), ('N_', 10075), ('A099', 9534), ('J00', 8541), ('J303', 7546), ('A090', 7366), ('L239', 6796), ('J040', 6510), ('H521', 6350), ('J_', 6222), ('J0190', 5885), ('K297', 5418), ('L209', 5349), ('K291', 5305), ('J40', 5296), ('J069', 5273), ('H101', 5212), ('S3350', 5036), ('K529', 4363), ('S9348', 4087), ('J329', 3677), ('K219', 3663), ('M5456', 3659), ('S9349', 3613), ('H001', 3592)], [('F_', 46897), ('J209', 42364), ('N_', 32992), ('J0390', 11645), ('L239', 10633), ('J304', 10063), ('J029', 9076), ('J060', 8208), ('A099', 8009), ('J00', 6645), ('B_', 6119), ('J040', 6081), ('K210', 5853), ('S3350', 5828), ('H0411', 5811), ('J303', 5740), ('H101', 5714), ('L209', 5671), ('K219', 5612), ('A090', 5547), ('A_', 5237), ('K297', 5160), ('J40', 5020), ('M5456', 4955), ('N300', 4702), ('K291', 4556), ('L238', 4401), ('M5422', 4278), ('J0190', 4180), ('J_', 4166)], [('N_', 53674), ('F_', 49983), ('J209', 49657), ('Z_', 16670), ('J0390', 14315), ('L239', 12206), ('J304', 11832), ('J029', 10505), ('J060', 10085), ('B_', 9847), ('A099', 9628), ('K210', 8828), ('S3350', 8494), ('M5422', 8260), ('J00', 8182), ('H0411', 7625), ('A_', 7625), ('M5456', 7532), ('K219', 7404), ('J040', 7315), ('O_', 7068), ('J303', 7022), ('J40', 6657), ('K297', 6647), ('N300', 6512), ('S134', 6432), ('A090', 6343), ('H101', 6166), ('K291', 5773), ('J_', 5444)], [('J209', 61782), ('N_', 55161), ('F_', 42333), ('Z_', 40906), ('O_', 18250), ('J0390', 15613), ('J304', 13287), ('J029', 12366), ('J060', 11420), ('L239', 10164), ('B_', 9514), ('K210', 9490), ('M5422', 9235), ('S3350', 9210), ('J00', 8945), ('J040', 8395), ('M5456', 8378), ('A099', 8069), ('J40', 7769), ('J303', 7526), ('M511', 7444), ('K219', 7373), ('S134', 6514), ('J0190', 6436), ('H0411', 6355), ('K297', 6322), ('A_', 6035), ('H101', 5603), ('N300', 5422), ('I109', 5371)], [('J209', 90301), ('N_', 56320), ('F_', 46723), ('Z_', 30426), ('J0390', 21270), ('J304', 18612), ('I109', 17066), ('J029', 16999), ('J060', 15495), ('O_', 14631), ('K210', 13313), ('S3350', 12697), ('L239', 12155), ('B_', 12129), ('J040', 11820), ('M5456', 11814), ('M511', 11417), ('M5422', 11350), ('J00', 11293), ('J40', 10743), ('J303', 10069), ('K219', 9712), ('J0190', 9616), ('E119', 9091), ('A099', 8264), ('S134', 7918), ('K297', 7794), ('H101', 7445), ('H0411', 7404), ('J_', 7146)], [('J209', 78969), ('N_', 51066), ('F_', 48614), ('I109', 38532), ('K210', 17802), ('J0390', 17631), ('J304', 17333), ('E119', 17140), ('M511', 14328), ('J029', 14320), ('J060', 14160), ('S3350', 13391), ('L239', 13135), ('M5456', 13017), ('B_', 12454), ('M5422', 11505), ('K219', 10885), ('J040', 10477), ('J00', 9922), ('J40', 9818), ('J303', 9531), ('M771', 9286), ('D_', 9201), ('H0411', 8883), ('N185', 8821), ('K297', 8629), ('S134', 8240), ('J0190', 7633), ('M501', 7217), ('Z_', 7169)], [('I109', 80308), ('J209', 73719), ('N_', 53832), ('F_', 53198), ('E119', 32049), ('K210', 20572), ('M511', 17773), ('M771', 16929), ('N185', 16815), ('L239', 16248), ('J304', 16094), ('J0390', 15939), ('S3350', 15920), ('M5456', 15760), ('J029', 13518), ('B_', 13512), ('J060', 13258), ('M5422', 13249), ('K219', 12718), ('D_', 12508), ('M750', 12254), ('M751', 12072), ('M501', 11996), ('C_', 11183), ('H0411', 11082), ('J00', 10313), ('J040', 9836), ('S134', 9734), ('K297', 9600), ('J40', 9506)], [('I109', 130126), ('J209', 67812), ('F_', 52255), ('N_', 51602), ('E119', 47820), ('K210', 24571), ('N185', 22571), ('M511', 22381), ('M750', 19390), ('L239', 18712), ('M5456', 18532), ('M771', 18139), ('M751', 17044), ('S3350', 16845), ('M501', 15253), ('J304', 14915), ('M170', 14845), ('M5422', 14767), ('K219', 14727), ('C_', 14022), ('J0390', 13772), ('B_', 13661), ('H0411', 13333), ('J029', 12743), ('J060', 12233), ('E785', 11052), ('J40', 10715), ('N300', 10622), ('B351', 10611), ('M4806', 10439)]]

[[('J209', 453412), ('J304', 70540), ('J00', 52162), ('J029', 51109), ('J0190', 48636), ('J219', 44081), ('J0390', 39613), ('J069', 32555), ('J303', 29313), ('H66000', 28448), ('B_', 23642), ('J189', 22102), ('J0100', 20094), ('H6690', 19839), ('A090', 19426), ('J_', 19028), ('J060', 16024), ('A099', 15703), ('H6640', 13937), ('J459', 13314), ('J040', 11168), ('J329', 11113), ('R509', 9119), ('J40', 9003), ('J22', 8994), ('J320', 8862), ('J180', 8399), ('L209', 7446), ('J0180', 7001), ('L509', 6721)], [('J209', 285705), ('J304', 59793), ('J0190', 31899), ('J029', 31073), ('J0390', 30371), ('J_', 26700), ('J303', 26278), ('J00', 24248), ('J069', 15160), ('J0100', 14833), ('J060', 14593), ('J219', 14281), ('H101', 13424), ('A090', 13415), ('J040', 12733), ('A099', 12307), ('J329', 10733), ('H66000', 10688), ('H521', 10155), ('J459', 9836), ('J189', 9803), ('F_', 9140), ('J320', 8455), ('J40', 7836), ('B_', 7421), ('H6690', 6843), ('L239', 5694), ('J22', 5694), ('J0180', 5687), ('L209', 5638)], [('J209', 91515), ('J304', 24530), ('J0390', 15874), ('J029', 14845), ('H521', 14606), ('F_', 14424), ('J_', 14088), ('J303', 11766), ('J060', 9914), ('J0190', 9793), ('J00', 8799), ('H101', 8293), ('A099', 8125), ('A090', 7535), ('J040', 7427), ('B07', 6353), ('J069', 5391), ('L239', 5322), ('J329', 5045), ('J0100', 4990), ('E_', 4754), ('J40', 4556), ('L209', 4369), ('H5221', 4020), ('J320', 3774), ('E228', 3648), ('S9348', 3484), ('J219', 3353), ('H0001', 3107), ('H001', 3067)], [('J209', 58184), ('F_', 25224), ('J304', 14001), ('J0390', 13834), ('J029', 12773), ('J060', 10253), ('N_', 10075), ('A099', 9534), ('J00', 8541), ('J303', 7546), ('A090', 7366), ('L239', 6796), ('J040', 6510), ('H521', 6350), ('J_', 6222), ('J0190', 5885), ('K297', 5418), ('L209', 5349), ('K291', 5305), ('J40', 5296), ('J069', 5273), ('H101', 5212), ('S3350', 5036), ('K529', 4363), ('S9348', 4087), ('J329', 3677), ('K219', 3663), ('M5456', 3659), ('S9349', 3613), ('H001', 3592)], [('F_', 46897), ('J209', 42364), ('N_', 32992), ('J0390', 11645), ('L239', 10633), ('J304', 10063), ('J029', 9076), ('J060', 8208), ('A099', 8009), ('J00', 6645), ('B_', 6119), ('J040', 6081), ('K210', 5853), ('S3350', 5828), ('H0411', 5811), ('J303', 5740), ('H101', 5714), ('L209', 5671), ('K219', 5612), ('A090', 5547), ('A_', 5237), ('K297', 5160), ('J40', 5020), ('M5456', 4955), ('N300', 4702), ('K291', 4556), ('L238', 4401), ('M5422', 4278), ('J0190', 4180), ('J_', 4166)], [('N_', 53674), ('F_', 49983), ('J209', 49657), ('Z_', 16670), ('J0390', 14315), ('L239', 12206), ('J304', 11832), ('J029', 10505), ('J060', 10085), ('B_', 9847), ('A099', 9628), ('K210', 8828), ('S3350', 8494), ('M5422', 8260), ('J00', 8182), ('H0411', 7625), ('A_', 7625), ('M5456', 7532), ('K219', 7404), ('J040', 7315), ('O_', 7068), ('J303', 7022), ('J40', 6657), ('K297', 6647), ('N300', 6512), ('S134', 6432), ('A090', 6343), ('H101', 6166), ('K291', 5773), ('J_', 5444)], [('J209', 61782), ('N_', 55161), ('F_', 42333), ('Z_', 40906), ('O_', 18250), ('J0390', 15613), ('J304', 13287), ('J029', 12366), ('J060', 11420), ('L239', 10164), ('B_', 9514), ('K210', 9490), ('M5422', 9235), ('S3350', 9210), ('J00', 8945), ('J040', 8395), ('M5456', 8378), ('A099', 8069), ('J40', 7769), ('J303', 7526), ('M511', 7444), ('K219', 7373), ('S134', 6514), ('J0190', 6436), ('H0411', 6355), ('K297', 6322), ('A_', 6035), ('H101', 5603), ('N300', 5422), ('I109', 5371)], [('J209', 90301), ('N_', 56320), ('F_', 46723), ('Z_', 30426), ('J0390', 21270), ('J304', 18612), ('I109', 17066), ('J029', 16999), ('J060', 15495), ('O_', 14631), ('K210', 13313), ('S3350', 12697), ('L239', 12155), ('B_', 12129), ('J040', 11820), ('M5456', 11814), ('M511', 11417), ('M5422', 11350), ('J00', 11293), ('J40', 10743), ('J303', 10069), ('K219', 9712), ('J0190', 9616), ('E119', 9091), ('A099', 8264), ('S134', 7918), ('K297', 7794), ('H101', 7445), ('H0411', 7404), ('J_', 7146)], [('J209', 78969), ('N_', 51066), ('F_', 48614), ('I109', 38532), ('K210', 17802), ('J0390', 17631), ('J304', 17333), ('E119', 17140), ('M511', 14328), ('J029', 14320), ('J060', 14160), ('S3350', 13391), ('L239', 13135), ('M5456', 13017), ('B_', 12454), ('M5422', 11505), ('K219', 10885), ('J040', 10477), ('J00', 9922), ('J40', 9818), ('J303', 9531), ('M771', 9286), ('D_', 9201), ('H0411', 8883), ('N185', 8821), ('K297', 8629), ('S134', 8240), ('J0190', 7633), ('M501', 7217), ('Z_', 7169)], [('I109', 80308), ('J209', 73719), ('N_', 53832), ('F_', 53198), ('E119', 32049), ('K210', 20572), ('M511', 17773), ('M771', 16929), ('N185', 16815), ('L239', 16248), ('J304', 16094), ('J0390', 15939), ('S3350', 15920), ('M5456', 15760), ('J029', 13518), ('B_', 13512), ('J060', 13258), ('M5422', 13249), ('K219', 12718), ('D_', 12508), ('M750', 12254), ('M751', 12072), ('M501', 11996), ('C_', 11183), ('H0411', 11082), ('J00', 10313), ('J040', 9836), ('S134', 9734), ('K297', 9600), ('J40', 9506)], [('I109', 130126), ('J209', 67812), ('F_', 52255), ('N_', 51602), ('E119', 47820), ('K210', 24571), ('N185', 22571), ('M511', 22381), ('M750', 19390), ('L239', 18712), ('M5456', 18532), ('M771', 18139), ('M751', 17044), ('S3350', 16845), ('M501', 15253), ('J304', 14915), ('M170', 14845), ('M5422', 14767), ('K219', 14727), ('C_', 14022), ('J0390', 13772), ('B_', 13661), ('H0411', 13333), ('J029', 12743), ('J060', 12233), ('E785', 11052), ('J40', 10715), ('N300', 10622), ('B351', 10611), ('M4806', 10439)], [('I109', 189099), ('J209', 73525), ('E119', 66715), ('F_', 56418), ('N_', 37444), ('M170', 32599), ('N185', 31974), ('K210', 28056), ('M511', 27982), ('M5456', 22983), ('L239', 20955), ('M4806', 20602), ('M751', 20282), ('M750', 20215), ('S3350', 17384), ('K219', 17291), ('M501', 16325), ('E785', 15983), ('H0411', 15462), ('J304', 14637), ('M771', 14422), ('J0390', 14157), ('M171', 13929), ('C_', 13680), ('J029', 13464), ('M5422', 13459), ('J060', 12899), ('E118', 12867), ('B_', 12274), ('B351', 12203)]]
[[('J209', 453412), ('J304', 70540), ('J00', 52162), ('J029', 51109), ('J0190', 48636), ('J219', 44081), ('J0390', 39613), ('J069', 32555), ('J303', 29313), ('H66000', 28448), ('B_', 23642), ('J189', 22102), ('J0100', 20094), ('H6690', 19839), ('A090', 19426), ('J_', 19028), ('J060', 16024), ('A099', 15703), ('H6640', 13937), ('J459', 13314), ('J040', 11168), ('J329', 11113), ('R509', 9119), ('J40', 9003), ('J22', 8994), ('J320', 8862), ('J180', 8399), ('L209', 7446), ('J0180', 7001), ('L509', 6721)], [('J209', 285705), ('J304', 59793), ('J0190', 31899), ('J029', 31073), ('J0390', 30371), ('J_', 26700), ('J303', 26278), ('J00', 24248), ('J069', 15160), ('J0100', 14833), ('J060', 14593), ('J219', 14281), ('H101', 13424), ('A090', 13415), ('J040', 12733), ('A099', 12307), ('J329', 10733), ('H66000', 10688), ('H521', 10155), ('J459', 9836), ('J189', 9803), ('F_', 9140), ('J320', 8455), ('J40', 7836), ('B_', 7421), ('H6690', 6843), ('L239', 5694), ('J22', 5694), ('J0180', 5687), ('L209', 5638)], [('J209', 91515), ('J304', 24530), ('J0390', 15874), ('J029', 14845), ('H521', 14606), ('F_', 14424), ('J_', 14088), ('J303', 11766), ('J060', 9914), ('J0190', 9793), ('J00', 8799), ('H101', 8293), ('A099', 8125), ('A090', 7535), ('J040', 7427), ('B07', 6353), ('J069', 5391), ('L239', 5322), ('J329', 5045), ('J0100', 4990), ('E_', 4754), ('J40', 4556), ('L209', 4369), ('H5221', 4020), ('J320', 3774), ('E228', 3648), ('S9348', 3484), ('J219', 3353), ('H0001', 3107), ('H001', 3067)], [('J209', 58184), ('F_', 25224), ('J304', 14001), ('J0390', 13834), ('J029', 12773), ('J060', 10253), ('N_', 10075), ('A099', 9534), ('J00', 8541), ('J303', 7546), ('A090', 7366), ('L239', 6796), ('J040', 6510), ('H521', 6350), ('J_', 6222), ('J0190', 5885), ('K297', 5418), ('L209', 5349), ('K291', 5305), ('J40', 5296), ('J069', 5273), ('H101', 5212), ('S3350', 5036), ('K529', 4363), ('S9348', 4087), ('J329', 3677), ('K219', 3663), ('M5456', 3659), ('S9349', 3613), ('H001', 3592)], [('F_', 46897), ('J209', 42364), ('N_', 32992), ('J0390', 11645), ('L239', 10633), ('J304', 10063), ('J029', 9076), ('J060', 8208), ('A099', 8009), ('J00', 6645), ('B_', 6119), ('J040', 6081), ('K210', 5853), ('S3350', 5828), ('H0411', 5811), ('J303', 5740), ('H101', 5714), ('L209', 5671), ('K219', 5612), ('A090', 5547), ('A_', 5237), ('K297', 5160), ('J40', 5020), ('M5456', 4955), ('N300', 4702), ('K291', 4556), ('L238', 4401), ('M5422', 4278), ('J0190', 4180), ('J_', 4166)], [('N_', 53674), ('F_', 49983), ('J209', 49657), ('Z_', 16670), ('J0390', 14315), ('L239', 12206), ('J304', 11832), ('J029', 10505), ('J060', 10085), ('B_', 9847), ('A099', 9628), ('K210', 8828), ('S3350', 8494), ('M5422', 8260), ('J00', 8182), ('H0411', 7625), ('A_', 7625), ('M5456', 7532), ('K219', 7404), ('J040', 7315), ('O_', 7068), ('J303', 7022), ('J40', 6657), ('K297', 6647), ('N300', 6512), ('S134', 6432), ('A090', 6343), ('H101', 6166), ('K291', 5773), ('J_', 5444)], [('J209', 61782), ('N_', 55161), ('F_', 42333), ('Z_', 40906), ('O_', 18250), ('J0390', 15613), ('J304', 13287), ('J029', 12366), ('J060', 11420), ('L239', 10164), ('B_', 9514), ('K210', 9490), ('M5422', 9235), ('S3350', 9210), ('J00', 8945), ('J040', 8395), ('M5456', 8378), ('A099', 8069), ('J40', 7769), ('J303', 7526), ('M511', 7444), ('K219', 7373), ('S134', 6514), ('J0190', 6436), ('H0411', 6355), ('K297', 6322), ('A_', 6035), ('H101', 5603), ('N300', 5422), ('I109', 5371)], [('J209', 90301), ('N_', 56320), ('F_', 46723), ('Z_', 30426), ('J0390', 21270), ('J304', 18612), ('I109', 17066), ('J029', 16999), ('J060', 15495), ('O_', 14631), ('K210', 13313), ('S3350', 12697), ('L239', 12155), ('B_', 12129), ('J040', 11820), ('M5456', 11814), ('M511', 11417), ('M5422', 11350), ('J00', 11293), ('J40', 10743), ('J303', 10069), ('K219', 9712), ('J0190', 9616), ('E119', 9091), ('A099', 8264), ('S134', 7918), ('K297', 7794), ('H101', 7445), ('H0411', 7404), ('J_', 7146)], [('J209', 78969), ('N_', 51066), ('F_', 48614), ('I109', 38532), ('K210', 17802), ('J0390', 17631), ('J304', 17333), ('E119', 17140), ('M511', 14328), ('J029', 14320), ('J060', 14160), ('S3350', 13391), ('L239', 13135), ('M5456', 13017), ('B_', 12454), ('M5422', 11505), ('K219', 10885), ('J040', 10477), ('J00', 9922), ('J40', 9818), ('J303', 9531), ('M771', 9286), ('D_', 9201), ('H0411', 8883), ('N185', 8821), ('K297', 8629), ('S134', 8240), ('J0190', 7633), ('M501', 7217), ('Z_', 7169)], [('I109', 80308), ('J209', 73719), ('N_', 53832), ('F_', 53198), ('E119', 32049), ('K210', 20572), ('M511', 17773), ('M771', 16929), ('N185', 16815), ('L239', 16248), ('J304', 16094), ('J0390', 15939), ('S3350', 15920), ('M5456', 15760), ('J029', 13518), ('B_', 13512), ('J060', 13258), ('M5422', 13249), ('K219', 12718), ('D_', 12508), ('M750', 12254), ('M751', 12072), ('M501', 11996), ('C_', 11183), ('H0411', 11082), ('J00', 10313), ('J040', 9836), ('S134', 9734), ('K297', 9600), ('J40', 9506)], [('I109', 130126), ('J209', 67812), ('F_', 52255), ('N_', 51602), ('E119', 47820), ('K210', 24571), ('N185', 22571), ('M511', 22381), ('M750', 19390), ('L239', 18712), ('M5456', 18532), ('M771', 18139), ('M751', 17044), ('S3350', 16845), ('M501', 15253), ('J304', 14915), ('M170', 14845), ('M5422', 14767), ('K219', 14727), ('C_', 14022), ('J0390', 13772), ('B_', 13661), ('H0411', 13333), ('J029', 12743), ('J060', 12233), ('E785', 11052), ('J40', 10715), ('N300', 10622), ('B351', 10611), ('M4806', 10439)], [('I109', 189099), ('J209', 73525), ('E119', 66715), ('F_', 56418), ('N_', 37444), ('M170', 32599), ('N185', 31974), ('K210', 28056), ('M511', 27982), ('M5456', 22983), ('L239', 20955), ('M4806', 20602), ('M751', 20282), ('M750', 20215), ('S3350', 17384), ('K219', 17291), ('M501', 16325), ('E785', 15983), ('H0411', 15462), ('J304', 14637), ('M771', 14422), ('J0390', 14157), ('M171', 13929), ('C_', 13680), ('J029', 13464), ('M5422', 13459), ('J060', 12899), ('E118', 12867), ('B_', 12274), ('B351', 12203)], [('I109', 235201), ('E119', 77857), ('J209', 76631), ('F_', 62748), ('M170', 51882), ('M4806', 36599), ('N185', 34514), ('K210', 33447), ('M511', 31088), ('N_', 27082), ('M5456', 26544), ('M751', 22052), ('L239', 21436), ('M171', 20827), ('K219', 19521), ('M750', 19483), ('E785', 17902), ('N400', 17538), ('S3350', 17389), ('H0411', 16610), ('M501', 16400), ('E118', 15570), ('M179', 14791), ('J304', 13867), ('J40', 13626), ('J029', 12969), ('J0390', 12936), ('J060', 12623), ('C_', 12586), ('B351', 12308)]]

[[('J209', 453412), ('J304', 70540), ('J00', 52162), ('J029', 51109), ('J0190', 48636), ('J219', 44081), ('J0390', 39613), ('J069', 32555), ('J303', 29313), ('H66000', 28448), ('B_', 23642), ('J189', 22102), ('J0100', 20094), ('H6690', 19839), ('A090', 19426), ('J_', 19028), ('J060', 16024), ('A099', 15703), ('H6640', 13937), ('J459', 13314), ('J040', 11168), ('J329', 11113), ('R509', 9119), ('J40', 9003), ('J22', 8994), ('J320', 8862), ('J180', 8399), ('L209', 7446), ('J0180', 7001), ('L509', 6721)], [('J209', 285705), ('J304', 59793), ('J0190', 31899), ('J029', 31073), ('J0390', 30371), ('J_', 26700), ('J303', 26278), ('J00', 24248), ('J069', 15160), ('J0100', 14833), ('J060', 14593), ('J219', 14281), ('H101', 13424), ('A090', 13415), ('J040', 12733), ('A099', 12307), ('J329', 10733), ('H66000', 10688), ('H521', 10155), ('J459', 9836), ('J189', 9803), ('F_', 9140), ('J320', 8455), ('J40', 7836), ('B_', 7421), ('H6690', 6843), ('L239', 5694), ('J22', 5694), ('J0180', 5687), ('L209', 5638)], [('J209', 91515), ('J304', 24530), ('J0390', 15874), ('J029', 14845), ('H521', 14606), ('F_', 14424), ('J_', 14088), ('J303', 11766), ('J060', 9914), ('J0190', 9793), ('J00', 8799), ('H101', 8293), ('A099', 8125), ('A090', 7535), ('J040', 7427), ('B07', 6353), ('J069', 5391), ('L239', 5322), ('J329', 5045), ('J0100', 4990), ('E_', 4754), ('J40', 4556), ('L209', 4369), ('H5221', 4020), ('J320', 3774), ('E228', 3648), ('S9348', 3484), ('J219', 3353), ('H0001', 3107), ('H001', 3067)], [('J209', 58184), ('F_', 25224), ('J304', 14001), ('J0390', 13834), ('J029', 12773), ('J060', 10253), ('N_', 10075), ('A099', 9534), ('J00', 8541), ('J303', 7546), ('A090', 7366), ('L239', 6796), ('J040', 6510), ('H521', 6350), ('J_', 6222), ('J0190', 5885), ('K297', 5418), ('L209', 5349), ('K291', 5305), ('J40', 5296), ('J069', 5273), ('H101', 5212), ('S3350', 5036), ('K529', 4363), ('S9348', 4087), ('J329', 3677), ('K219', 3663), ('M5456', 3659), ('S9349', 3613), ('H001', 3592)], [('F_', 46897), ('J209', 42364), ('N_', 32992), ('J0390', 11645), ('L239', 10633), ('J304', 10063), ('J029', 9076), ('J060', 8208), ('A099', 8009), ('J00', 6645), ('B_', 6119), ('J040', 6081), ('K210', 5853), ('S3350', 5828), ('H0411', 5811), ('J303', 5740), ('H101', 5714), ('L209', 5671), ('K219', 5612), ('A090', 5547), ('A_', 5237), ('K297', 5160), ('J40', 5020), ('M5456', 4955), ('N300', 4702), ('K291', 4556), ('L238', 4401), ('M5422', 4278), ('J0190', 4180), ('J_', 4166)], [('N_', 53674), ('F_', 49983), ('J209', 49657), ('Z_', 16670), ('J0390', 14315), ('L239', 12206), ('J304', 11832), ('J029', 10505), ('J060', 10085), ('B_', 9847), ('A099', 9628), ('K210', 8828), ('S3350', 8494), ('M5422', 8260), ('J00', 8182), ('H0411', 7625), ('A_', 7625), ('M5456', 7532), ('K219', 7404), ('J040', 7315), ('O_', 7068), ('J303', 7022), ('J40', 6657), ('K297', 6647), ('N300', 6512), ('S134', 6432), ('A090', 6343), ('H101', 6166), ('K291', 5773), ('J_', 5444)], [('J209', 61782), ('N_', 55161), ('F_', 42333), ('Z_', 40906), ('O_', 18250), ('J0390', 15613), ('J304', 13287), ('J029', 12366), ('J060', 11420), ('L239', 10164), ('B_', 9514), ('K210', 9490), ('M5422', 9235), ('S3350', 9210), ('J00', 8945), ('J040', 8395), ('M5456', 8378), ('A099', 8069), ('J40', 7769), ('J303', 7526), ('M511', 7444), ('K219', 7373), ('S134', 6514), ('J0190', 6436), ('H0411', 6355), ('K297', 6322), ('A_', 6035), ('H101', 5603), ('N300', 5422), ('I109', 5371)], [('J209', 90301), ('N_', 56320), ('F_', 46723), ('Z_', 30426), ('J0390', 21270), ('J304', 18612), ('I109', 17066), ('J029', 16999), ('J060', 15495), ('O_', 14631), ('K210', 13313), ('S3350', 12697), ('L239', 12155), ('B_', 12129), ('J040', 11820), ('M5456', 11814), ('M511', 11417), ('M5422', 11350), ('J00', 11293), ('J40', 10743), ('J303', 10069), ('K219', 9712), ('J0190', 9616), ('E119', 9091), ('A099', 8264), ('S134', 7918), ('K297', 7794), ('H101', 7445), ('H0411', 7404), ('J_', 7146)], [('J209', 78969), ('N_', 51066), ('F_', 48614), ('I109', 38532), ('K210', 17802), ('J0390', 17631), ('J304', 17333), ('E119', 17140), ('M511', 14328), ('J029', 14320), ('J060', 14160), ('S3350', 13391), ('L239', 13135), ('M5456', 13017), ('B_', 12454), ('M5422', 11505), ('K219', 10885), ('J040', 10477), ('J00', 9922), ('J40', 9818), ('J303', 9531), ('M771', 9286), ('D_', 9201), ('H0411', 8883), ('N185', 8821), ('K297', 8629), ('S134', 8240), ('J0190', 7633), ('M501', 7217), ('Z_', 7169)], [('I109', 80308), ('J209', 73719), ('N_', 53832), ('F_', 53198), ('E119', 32049), ('K210', 20572), ('M511', 17773), ('M771', 16929), ('N185', 16815), ('L239', 16248), ('J304', 16094), ('J0390', 15939), ('S3350', 15920), ('M5456', 15760), ('J029', 13518), ('B_', 13512), ('J060', 13258), ('M5422', 13249), ('K219', 12718), ('D_', 12508), ('M750', 12254), ('M751', 12072), ('M501', 11996), ('C_', 11183), ('H0411', 11082), ('J00', 10313), ('J040', 9836), ('S134', 9734), ('K297', 9600), ('J40', 9506)], [('I109', 130126), ('J209', 67812), ('F_', 52255), ('N_', 51602), ('E119', 47820), ('K210', 24571), ('N185', 22571), ('M511', 22381), ('M750', 19390), ('L239', 18712), ('M5456', 18532), ('M771', 18139), ('M751', 17044), ('S3350', 16845), ('M501', 15253), ('J304', 14915), ('M170', 14845), ('M5422', 14767), ('K219', 14727), ('C_', 14022), ('J0390', 13772), ('B_', 13661), ('H0411', 13333), ('J029', 12743), ('J060', 12233), ('E785', 11052), ('J40', 10715), ('N300', 10622), ('B351', 10611), ('M4806', 10439)], [('I109', 189099), ('J209', 73525), ('E119', 66715), ('F_', 56418), ('N_', 37444), ('M170', 32599), ('N185', 31974), ('K210', 28056), ('M511', 27982), ('M5456', 22983), ('L239', 20955), ('M4806', 20602), ('M751', 20282), ('M750', 20215), ('S3350', 17384), ('K219', 17291), ('M501', 16325), ('E785', 15983), ('H0411', 15462), ('J304', 14637), ('M771', 14422), ('J0390', 14157), ('M171', 13929), ('C_', 13680), ('J029', 13464), ('M5422', 13459), ('J060', 12899), ('E118', 12867), ('B_', 12274), ('B351', 12203)], [('I109', 235201), ('E119', 77857), ('J209', 76631), ('F_', 62748), ('M170', 51882), ('M4806', 36599), ('N185', 34514), ('K210', 33447), ('M511', 31088), ('N_', 27082), ('M5456', 26544), ('M751', 22052), ('L239', 21436), ('M171', 20827), ('K219', 19521), ('M750', 19483), ('E785', 17902), ('N400', 17538), ('S3350', 17389), ('H0411', 16610), ('M501', 16400), ('E118', 15570), ('M179', 14791), ('J304', 13867), ('J40', 13626), ('J029', 12969), ('J0390', 12936), ('J060', 12623), ('C_', 12586), ('B351', 12308)], [('I109', 214517), ('E119', 67757), ('J209', 63102), ('M170', 60053), ('F_', 56135), ('M4806', 48061), ('N185', 36391), ('M5456', 28926), ('M511', 27860), ('K210', 26186), ('M171', 23201), ('N400', 20465), ('M751', 18302), ('L239', 18092), ('M750', 17095), ('K219', 16937), ('M179', 16624), ('H0411', 14592), ('S3350', 14207), ('N_', 13917), ('E118', 13709), ('E785', 13590), ('J40', 11955), ('M501', 11674), ('J304', 11115), ('J00', 10618), ('M5422', 10493), ('K297', 10346), ('J029', 10283), ('J060', 10207)]]
[[('J209', 453412), ('J304', 70540), ('J00', 52162), ('J029', 51109), ('J0190', 48636), ('J219', 44081), ('J0390', 39613), ('J069', 32555), ('J303', 29313), ('H66000', 28448), ('B_', 23642), ('J189', 22102), ('J0100', 20094), ('H6690', 19839), ('A090', 19426), ('J_', 19028), ('J060', 16024), ('A099', 15703), ('H6640', 13937), ('J459', 13314), ('J040', 11168), ('J329', 11113), ('R509', 9119), ('J40', 9003), ('J22', 8994), ('J320', 8862), ('J180', 8399), ('L209', 7446), ('J0180', 7001), ('L509', 6721)], [('J209', 285705), ('J304', 59793), ('J0190', 31899), ('J029', 31073), ('J0390', 30371), ('J_', 26700), ('J303', 26278), ('J00', 24248), ('J069', 15160), ('J0100', 14833), ('J060', 14593), ('J219', 14281), ('H101', 13424), ('A090', 13415), ('J040', 12733), ('A099', 12307), ('J329', 10733), ('H66000', 10688), ('H521', 10155), ('J459', 9836), ('J189', 9803), ('F_', 9140), ('J320', 8455), ('J40', 7836), ('B_', 7421), ('H6690', 6843), ('L239', 5694), ('J22', 5694), ('J0180', 5687), ('L209', 5638)], [('J209', 91515), ('J304', 24530), ('J0390', 15874), ('J029', 14845), ('H521', 14606), ('F_', 14424), ('J_', 14088), ('J303', 11766), ('J060', 9914), ('J0190', 9793), ('J00', 8799), ('H101', 8293), ('A099', 8125), ('A090', 7535), ('J040', 7427), ('B07', 6353), ('J069', 5391), ('L239', 5322), ('J329', 5045), ('J0100', 4990), ('E_', 4754), ('J40', 4556), ('L209', 4369), ('H5221', 4020), ('J320', 3774), ('E228', 3648), ('S9348', 3484), ('J219', 3353), ('H0001', 3107), ('H001', 3067)], [('J209', 58184), ('F_', 25224), ('J304', 14001), ('J0390', 13834), ('J029', 12773), ('J060', 10253), ('N_', 10075), ('A099', 9534), ('J00', 8541), ('J303', 7546), ('A090', 7366), ('L239', 6796), ('J040', 6510), ('H521', 6350), ('J_', 6222), ('J0190', 5885), ('K297', 5418), ('L209', 5349), ('K291', 5305), ('J40', 5296), ('J069', 5273), ('H101', 5212), ('S3350', 5036), ('K529', 4363), ('S9348', 4087), ('J329', 3677), ('K219', 3663), ('M5456', 3659), ('S9349', 3613), ('H001', 3592)], [('F_', 46897), ('J209', 42364), ('N_', 32992), ('J0390', 11645), ('L239', 10633), ('J304', 10063), ('J029', 9076), ('J060', 8208), ('A099', 8009), ('J00', 6645), ('B_', 6119), ('J040', 6081), ('K210', 5853), ('S3350', 5828), ('H0411', 5811), ('J303', 5740), ('H101', 5714), ('L209', 5671), ('K219', 5612), ('A090', 5547), ('A_', 5237), ('K297', 5160), ('J40', 5020), ('M5456', 4955), ('N300', 4702), ('K291', 4556), ('L238', 4401), ('M5422', 4278), ('J0190', 4180), ('J_', 4166)], [('N_', 53674), ('F_', 49983), ('J209', 49657), ('Z_', 16670), ('J0390', 14315), ('L239', 12206), ('J304', 11832), ('J029', 10505), ('J060', 10085), ('B_', 9847), ('A099', 9628), ('K210', 8828), ('S3350', 8494), ('M5422', 8260), ('J00', 8182), ('H0411', 7625), ('A_', 7625), ('M5456', 7532), ('K219', 7404), ('J040', 7315), ('O_', 7068), ('J303', 7022), ('J40', 6657), ('K297', 6647), ('N300', 6512), ('S134', 6432), ('A090', 6343), ('H101', 6166), ('K291', 5773), ('J_', 5444)], [('J209', 61782), ('N_', 55161), ('F_', 42333), ('Z_', 40906), ('O_', 18250), ('J0390', 15613), ('J304', 13287), ('J029', 12366), ('J060', 11420), ('L239', 10164), ('B_', 9514), ('K210', 9490), ('M5422', 9235), ('S3350', 9210), ('J00', 8945), ('J040', 8395), ('M5456', 8378), ('A099', 8069), ('J40', 7769), ('J303', 7526), ('M511', 7444), ('K219', 7373), ('S134', 6514), ('J0190', 6436), ('H0411', 6355), ('K297', 6322), ('A_', 6035), ('H101', 5603), ('N300', 5422), ('I109', 5371)], [('J209', 90301), ('N_', 56320), ('F_', 46723), ('Z_', 30426), ('J0390', 21270), ('J304', 18612), ('I109', 17066), ('J029', 16999), ('J060', 15495), ('O_', 14631), ('K210', 13313), ('S3350', 12697), ('L239', 12155), ('B_', 12129), ('J040', 11820), ('M5456', 11814), ('M511', 11417), ('M5422', 11350), ('J00', 11293), ('J40', 10743), ('J303', 10069), ('K219', 9712), ('J0190', 9616), ('E119', 9091), ('A099', 8264), ('S134', 7918), ('K297', 7794), ('H101', 7445), ('H0411', 7404), ('J_', 7146)], [('J209', 78969), ('N_', 51066), ('F_', 48614), ('I109', 38532), ('K210', 17802), ('J0390', 17631), ('J304', 17333), ('E119', 17140), ('M511', 14328), ('J029', 14320), ('J060', 14160), ('S3350', 13391), ('L239', 13135), ('M5456', 13017), ('B_', 12454), ('M5422', 11505), ('K219', 10885), ('J040', 10477), ('J00', 9922), ('J40', 9818), ('J303', 9531), ('M771', 9286), ('D_', 9201), ('H0411', 8883), ('N185', 8821), ('K297', 8629), ('S134', 8240), ('J0190', 7633), ('M501', 7217), ('Z_', 7169)], [('I109', 80308), ('J209', 73719), ('N_', 53832), ('F_', 53198), ('E119', 32049), ('K210', 20572), ('M511', 17773), ('M771', 16929), ('N185', 16815), ('L239', 16248), ('J304', 16094), ('J0390', 15939), ('S3350', 15920), ('M5456', 15760), ('J029', 13518), ('B_', 13512), ('J060', 13258), ('M5422', 13249), ('K219', 12718), ('D_', 12508), ('M750', 12254), ('M751', 12072), ('M501', 11996), ('C_', 11183), ('H0411', 11082), ('J00', 10313), ('J040', 9836), ('S134', 9734), ('K297', 9600), ('J40', 9506)], [('I109', 130126), ('J209', 67812), ('F_', 52255), ('N_', 51602), ('E119', 47820), ('K210', 24571), ('N185', 22571), ('M511', 22381), ('M750', 19390), ('L239', 18712), ('M5456', 18532), ('M771', 18139), ('M751', 17044), ('S3350', 16845), ('M501', 15253), ('J304', 14915), ('M170', 14845), ('M5422', 14767), ('K219', 14727), ('C_', 14022), ('J0390', 13772), ('B_', 13661), ('H0411', 13333), ('J029', 12743), ('J060', 12233), ('E785', 11052), ('J40', 10715), ('N300', 10622), ('B351', 10611), ('M4806', 10439)], [('I109', 189099), ('J209', 73525), ('E119', 66715), ('F_', 56418), ('N_', 37444), ('M170', 32599), ('N185', 31974), ('K210', 28056), ('M511', 27982), ('M5456', 22983), ('L239', 20955), ('M4806', 20602), ('M751', 20282), ('M750', 20215), ('S3350', 17384), ('K219', 17291), ('M501', 16325), ('E785', 15983), ('H0411', 15462), ('J304', 14637), ('M771', 14422), ('J0390', 14157), ('M171', 13929), ('C_', 13680), ('J029', 13464), ('M5422', 13459), ('J060', 12899), ('E118', 12867), ('B_', 12274), ('B351', 12203)], [('I109', 235201), ('E119', 77857), ('J209', 76631), ('F_', 62748), ('M170', 51882), ('M4806', 36599), ('N185', 34514), ('K210', 33447), ('M511', 31088), ('N_', 27082), ('M5456', 26544), ('M751', 22052), ('L239', 21436), ('M171', 20827), ('K219', 19521), ('M750', 19483), ('E785', 17902), ('N400', 17538), ('S3350', 17389), ('H0411', 16610), ('M501', 16400), ('E118', 15570), ('M179', 14791), ('J304', 13867), ('J40', 13626), ('J029', 12969), ('J0390', 12936), ('J060', 12623), ('C_', 12586), ('B351', 12308)], [('I109', 214517), ('E119', 67757), ('J209', 63102), ('M170', 60053), ('F_', 56135), ('M4806', 48061), ('N185', 36391), ('M5456', 28926), ('M511', 27860), ('K210', 26186), ('M171', 23201), ('N400', 20465), ('M751', 18302), ('L239', 18092), ('M750', 17095), ('K219', 16937), ('M179', 16624), ('H0411', 14592), ('S3350', 14207), ('N_', 13917), ('E118', 13709), ('E785', 13590), ('J40', 11955), ('M501', 11674), ('J304', 11115), ('J00', 10618), ('M5422', 10493), ('K297', 10346), ('J029', 10283), ('J060', 10207)], [('I109', 194597), ('F_', 59601), ('E119', 58231), ('M170', 56671), ('M4806', 55830), ('J209', 52696), ('N185', 39619), ('M5456', 31374), ('M511', 24575), ('N400', 24376), ('K210', 23477), ('M171', 20368), ('M179', 17011), ('L239', 16595), ('H0411', 14552), ('K219', 14253), ('E118', 13400), ('M751', 13189), ('M750', 12389), ('S3350', 11372), ('J40', 10878), ('M501', 10431), ('I639', 9919), ('J304', 9869), ('J00', 9562), ('E785', 9361), ('C_', 9326), ('I209', 9232), ('K297', 9229), ('N401', 8731)]]

[[('J209', 453412), ('J304', 70540), ('J00', 52162), ('J029', 51109), ('J0190', 48636), ('J219', 44081), ('J0390', 39613), ('J069', 32555), ('J303', 29313), ('H66000', 28448), ('B_', 23642), ('J189', 22102), ('J0100', 20094), ('H6690', 19839), ('A090', 19426), ('J_', 19028), ('J060', 16024), ('A099', 15703), ('H6640', 13937), ('J459', 13314), ('J040', 11168), ('J329', 11113), ('R509', 9119), ('J40', 9003), ('J22', 8994), ('J320', 8862), ('J180', 8399), ('L209', 7446), ('J0180', 7001), ('L509', 6721)], [('J209', 285705), ('J304', 59793), ('J0190', 31899), ('J029', 31073), ('J0390', 30371), ('J_', 26700), ('J303', 26278), ('J00', 24248), ('J069', 15160), ('J0100', 14833), ('J060', 14593), ('J219', 14281), ('H101', 13424), ('A090', 13415), ('J040', 12733), ('A099', 12307), ('J329', 10733), ('H66000', 10688), ('H521', 10155), ('J459', 9836), ('J189', 9803), ('F_', 9140), ('J320', 8455), ('J40', 7836), ('B_', 7421), ('H6690', 6843), ('L239', 5694), ('J22', 5694), ('J0180', 5687), ('L209', 5638)], [('J209', 91515), ('J304', 24530), ('J0390', 15874), ('J029', 14845), ('H521', 14606), ('F_', 14424), ('J_', 14088), ('J303', 11766), ('J060', 9914), ('J0190', 9793), ('J00', 8799), ('H101', 8293), ('A099', 8125), ('A090', 7535), ('J040', 7427), ('B07', 6353), ('J069', 5391), ('L239', 5322), ('J329', 5045), ('J0100', 4990), ('E_', 4754), ('J40', 4556), ('L209', 4369), ('H5221', 4020), ('J320', 3774), ('E228', 3648), ('S9348', 3484), ('J219', 3353), ('H0001', 3107), ('H001', 3067)], [('J209', 58184), ('F_', 25224), ('J304', 14001), ('J0390', 13834), ('J029', 12773), ('J060', 10253), ('N_', 10075), ('A099', 9534), ('J00', 8541), ('J303', 7546), ('A090', 7366), ('L239', 6796), ('J040', 6510), ('H521', 6350), ('J_', 6222), ('J0190', 5885), ('K297', 5418), ('L209', 5349), ('K291', 5305), ('J40', 5296), ('J069', 5273), ('H101', 5212), ('S3350', 5036), ('K529', 4363), ('S9348', 4087), ('J329', 3677), ('K219', 3663), ('M5456', 3659), ('S9349', 3613), ('H001', 3592)], [('F_', 46897), ('J209', 42364), ('N_', 32992), ('J0390', 11645), ('L239', 10633), ('J304', 10063), ('J029', 9076), ('J060', 8208), ('A099', 8009), ('J00', 6645), ('B_', 6119), ('J040', 6081), ('K210', 5853), ('S3350', 5828), ('H0411', 5811), ('J303', 5740), ('H101', 5714), ('L209', 5671), ('K219', 5612), ('A090', 5547), ('A_', 5237), ('K297', 5160), ('J40', 5020), ('M5456', 4955), ('N300', 4702), ('K291', 4556), ('L238', 4401), ('M5422', 4278), ('J0190', 4180), ('J_', 4166)], [('N_', 53674), ('F_', 49983), ('J209', 49657), ('Z_', 16670), ('J0390', 14315), ('L239', 12206), ('J304', 11832), ('J029', 10505), ('J060', 10085), ('B_', 9847), ('A099', 9628), ('K210', 8828), ('S3350', 8494), ('M5422', 8260), ('J00', 8182), ('H0411', 7625), ('A_', 7625), ('M5456', 7532), ('K219', 7404), ('J040', 7315), ('O_', 7068), ('J303', 7022), ('J40', 6657), ('K297', 6647), ('N300', 6512), ('S134', 6432), ('A090', 6343), ('H101', 6166), ('K291', 5773), ('J_', 5444)], [('J209', 61782), ('N_', 55161), ('F_', 42333), ('Z_', 40906), ('O_', 18250), ('J0390', 15613), ('J304', 13287), ('J029', 12366), ('J060', 11420), ('L239', 10164), ('B_', 9514), ('K210', 9490), ('M5422', 9235), ('S3350', 9210), ('J00', 8945), ('J040', 8395), ('M5456', 8378), ('A099', 8069), ('J40', 7769), ('J303', 7526), ('M511', 7444), ('K219', 7373), ('S134', 6514), ('J0190', 6436), ('H0411', 6355), ('K297', 6322), ('A_', 6035), ('H101', 5603), ('N300', 5422), ('I109', 5371)], [('J209', 90301), ('N_', 56320), ('F_', 46723), ('Z_', 30426), ('J0390', 21270), ('J304', 18612), ('I109', 17066), ('J029', 16999), ('J060', 15495), ('O_', 14631), ('K210', 13313), ('S3350', 12697), ('L239', 12155), ('B_', 12129), ('J040', 11820), ('M5456', 11814), ('M511', 11417), ('M5422', 11350), ('J00', 11293), ('J40', 10743), ('J303', 10069), ('K219', 9712), ('J0190', 9616), ('E119', 9091), ('A099', 8264), ('S134', 7918), ('K297', 7794), ('H101', 7445), ('H0411', 7404), ('J_', 7146)], [('J209', 78969), ('N_', 51066), ('F_', 48614), ('I109', 38532), ('K210', 17802), ('J0390', 17631), ('J304', 17333), ('E119', 17140), ('M511', 14328), ('J029', 14320), ('J060', 14160), ('S3350', 13391), ('L239', 13135), ('M5456', 13017), ('B_', 12454), ('M5422', 11505), ('K219', 10885), ('J040', 10477), ('J00', 9922), ('J40', 9818), ('J303', 9531), ('M771', 9286), ('D_', 9201), ('H0411', 8883), ('N185', 8821), ('K297', 8629), ('S134', 8240), ('J0190', 7633), ('M501', 7217), ('Z_', 7169)], [('I109', 80308), ('J209', 73719), ('N_', 53832), ('F_', 53198), ('E119', 32049), ('K210', 20572), ('M511', 17773), ('M771', 16929), ('N185', 16815), ('L239', 16248), ('J304', 16094), ('J0390', 15939), ('S3350', 15920), ('M5456', 15760), ('J029', 13518), ('B_', 13512), ('J060', 13258), ('M5422', 13249), ('K219', 12718), ('D_', 12508), ('M750', 12254), ('M751', 12072), ('M501', 11996), ('C_', 11183), ('H0411', 11082), ('J00', 10313), ('J040', 9836), ('S134', 9734), ('K297', 9600), ('J40', 9506)], [('I109', 130126), ('J209', 67812), ('F_', 52255), ('N_', 51602), ('E119', 47820), ('K210', 24571), ('N185', 22571), ('M511', 22381), ('M750', 19390), ('L239', 18712), ('M5456', 18532), ('M771', 18139), ('M751', 17044), ('S3350', 16845), ('M501', 15253), ('J304', 14915), ('M170', 14845), ('M5422', 14767), ('K219', 14727), ('C_', 14022), ('J0390', 13772), ('B_', 13661), ('H0411', 13333), ('J029', 12743), ('J060', 12233), ('E785', 11052), ('J40', 10715), ('N300', 10622), ('B351', 10611), ('M4806', 10439)], [('I109', 189099), ('J209', 73525), ('E119', 66715), ('F_', 56418), ('N_', 37444), ('M170', 32599), ('N185', 31974), ('K210', 28056), ('M511', 27982), ('M5456', 22983), ('L239', 20955), ('M4806', 20602), ('M751', 20282), ('M750', 20215), ('S3350', 17384), ('K219', 17291), ('M501', 16325), ('E785', 15983), ('H0411', 15462), ('J304', 14637), ('M771', 14422), ('J0390', 14157), ('M171', 13929), ('C_', 13680), ('J029', 13464), ('M5422', 13459), ('J060', 12899), ('E118', 12867), ('B_', 12274), ('B351', 12203)], [('I109', 235201), ('E119', 77857), ('J209', 76631), ('F_', 62748), ('M170', 51882), ('M4806', 36599), ('N185', 34514), ('K210', 33447), ('M511', 31088), ('N_', 27082), ('M5456', 26544), ('M751', 22052), ('L239', 21436), ('M171', 20827), ('K219', 19521), ('M750', 19483), ('E785', 17902), ('N400', 17538), ('S3350', 17389), ('H0411', 16610), ('M501', 16400), ('E118', 15570), ('M179', 14791), ('J304', 13867), ('J40', 13626), ('J029', 12969), ('J0390', 12936), ('J060', 12623), ('C_', 12586), ('B351', 12308)], [('I109', 214517), ('E119', 67757), ('J209', 63102), ('M170', 60053), ('F_', 56135), ('M4806', 48061), ('N185', 36391), ('M5456', 28926), ('M511', 27860), ('K210', 26186), ('M171', 23201), ('N400', 20465), ('M751', 18302), ('L239', 18092), ('M750', 17095), ('K219', 16937), ('M179', 16624), ('H0411', 14592), ('S3350', 14207), ('N_', 13917), ('E118', 13709), ('E785', 13590), ('J40', 11955), ('M501', 11674), ('J304', 11115), ('J00', 10618), ('M5422', 10493), ('K297', 10346), ('J029', 10283), ('J060', 10207)], [('I109', 194597), ('F_', 59601), ('E119', 58231), ('M170', 56671), ('M4806', 55830), ('J209', 52696), ('N185', 39619), ('M5456', 31374), ('M511', 24575), ('N400', 24376), ('K210', 23477), ('M171', 20368), ('M179', 17011), ('L239', 16595), ('H0411', 14552), ('K219', 14253), ('E118', 13400), ('M751', 13189), ('M750', 12389), ('S3350', 11372), ('J40', 10878), ('M501', 10431), ('I639', 9919), ('J304', 9869), ('J00', 9562), ('E785', 9361), ('C_', 9326), ('I209', 9232), ('K297', 9229), ('N401', 8731)], [('I109', 177714), ('F_', 69903), ('M4806', 62135), ('M170', 49359), ('E119', 49223), ('J209', 43879), ('M5456', 34738), ('N185', 30377), ('M511', 21907), ('N400', 21310), ('K210', 18624), ('M171', 16903), ('M179', 16654), ('L239', 14362), ('H0411', 13406), ('I639', 12286), ('K219', 11821), ('E118', 11449), ('M750', 10117), ('M4807', 9515), ('J40', 9456), ('M751', 9406), ('J00', 9232), ('M5446', 8776), ('I209', 8754), ('C_', 8607), ('S3350', 8522), ('N401', 8055), ('G20', 8006), ('J304', 7927)]]
[[('J209', 453412), ('J304', 70540), ('J00', 52162), ('J029', 51109), ('J0190', 48636), ('J219', 44081), ('J0390', 39613), ('J069', 32555), ('J303', 29313), ('H66000', 28448), ('B_', 23642), ('J189', 22102), ('J0100', 20094), ('H6690', 19839), ('A090', 19426), ('J_', 19028), ('J060', 16024), ('A099', 15703), ('H6640', 13937), ('J459', 13314), ('J040', 11168), ('J329', 11113), ('R509', 9119), ('J40', 9003), ('J22', 8994), ('J320', 8862), ('J180', 8399), ('L209', 7446), ('J0180', 7001), ('L509', 6721)], [('J209', 285705), ('J304', 59793), ('J0190', 31899), ('J029', 31073), ('J0390', 30371), ('J_', 26700), ('J303', 26278), ('J00', 24248), ('J069', 15160), ('J0100', 14833), ('J060', 14593), ('J219', 14281), ('H101', 13424), ('A090', 13415), ('J040', 12733), ('A099', 12307), ('J329', 10733), ('H66000', 10688), ('H521', 10155), ('J459', 9836), ('J189', 9803), ('F_', 9140), ('J320', 8455), ('J40', 7836), ('B_', 7421), ('H6690', 6843), ('L239', 5694), ('J22', 5694), ('J0180', 5687), ('L209', 5638)], [('J209', 91515), ('J304', 24530), ('J0390', 15874), ('J029', 14845), ('H521', 14606), ('F_', 14424), ('J_', 14088), ('J303', 11766), ('J060', 9914), ('J0190', 9793), ('J00', 8799), ('H101', 8293), ('A099', 8125), ('A090', 7535), ('J040', 7427), ('B07', 6353), ('J069', 5391), ('L239', 5322), ('J329', 5045), ('J0100', 4990), ('E_', 4754), ('J40', 4556), ('L209', 4369), ('H5221', 4020), ('J320', 3774), ('E228', 3648), ('S9348', 3484), ('J219', 3353), ('H0001', 3107), ('H001', 3067)], [('J209', 58184), ('F_', 25224), ('J304', 14001), ('J0390', 13834), ('J029', 12773), ('J060', 10253), ('N_', 10075), ('A099', 9534), ('J00', 8541), ('J303', 7546), ('A090', 7366), ('L239', 6796), ('J040', 6510), ('H521', 6350), ('J_', 6222), ('J0190', 5885), ('K297', 5418), ('L209', 5349), ('K291', 5305), ('J40', 5296), ('J069', 5273), ('H101', 5212), ('S3350', 5036), ('K529', 4363), ('S9348', 4087), ('J329', 3677), ('K219', 3663), ('M5456', 3659), ('S9349', 3613), ('H001', 3592)], [('F_', 46897), ('J209', 42364), ('N_', 32992), ('J0390', 11645), ('L239', 10633), ('J304', 10063), ('J029', 9076), ('J060', 8208), ('A099', 8009), ('J00', 6645), ('B_', 6119), ('J040', 6081), ('K210', 5853), ('S3350', 5828), ('H0411', 5811), ('J303', 5740), ('H101', 5714), ('L209', 5671), ('K219', 5612), ('A090', 5547), ('A_', 5237), ('K297', 5160), ('J40', 5020), ('M5456', 4955), ('N300', 4702), ('K291', 4556), ('L238', 4401), ('M5422', 4278), ('J0190', 4180), ('J_', 4166)], [('N_', 53674), ('F_', 49983), ('J209', 49657), ('Z_', 16670), ('J0390', 14315), ('L239', 12206), ('J304', 11832), ('J029', 10505), ('J060', 10085), ('B_', 9847), ('A099', 9628), ('K210', 8828), ('S3350', 8494), ('M5422', 8260), ('J00', 8182), ('H0411', 7625), ('A_', 7625), ('M5456', 7532), ('K219', 7404), ('J040', 7315), ('O_', 7068), ('J303', 7022), ('J40', 6657), ('K297', 6647), ('N300', 6512), ('S134', 6432), ('A090', 6343), ('H101', 6166), ('K291', 5773), ('J_', 5444)], [('J209', 61782), ('N_', 55161), ('F_', 42333), ('Z_', 40906), ('O_', 18250), ('J0390', 15613), ('J304', 13287), ('J029', 12366), ('J060', 11420), ('L239', 10164), ('B_', 9514), ('K210', 9490), ('M5422', 9235), ('S3350', 9210), ('J00', 8945), ('J040', 8395), ('M5456', 8378), ('A099', 8069), ('J40', 7769), ('J303', 7526), ('M511', 7444), ('K219', 7373), ('S134', 6514), ('J0190', 6436), ('H0411', 6355), ('K297', 6322), ('A_', 6035), ('H101', 5603), ('N300', 5422), ('I109', 5371)], [('J209', 90301), ('N_', 56320), ('F_', 46723), ('Z_', 30426), ('J0390', 21270), ('J304', 18612), ('I109', 17066), ('J029', 16999), ('J060', 15495), ('O_', 14631), ('K210', 13313), ('S3350', 12697), ('L239', 12155), ('B_', 12129), ('J040', 11820), ('M5456', 11814), ('M511', 11417), ('M5422', 11350), ('J00', 11293), ('J40', 10743), ('J303', 10069), ('K219', 9712), ('J0190', 9616), ('E119', 9091), ('A099', 8264), ('S134', 7918), ('K297', 7794), ('H101', 7445), ('H0411', 7404), ('J_', 7146)], [('J209', 78969), ('N_', 51066), ('F_', 48614), ('I109', 38532), ('K210', 17802), ('J0390', 17631), ('J304', 17333), ('E119', 17140), ('M511', 14328), ('J029', 14320), ('J060', 14160), ('S3350', 13391), ('L239', 13135), ('M5456', 13017), ('B_', 12454), ('M5422', 11505), ('K219', 10885), ('J040', 10477), ('J00', 9922), ('J40', 9818), ('J303', 9531), ('M771', 9286), ('D_', 9201), ('H0411', 8883), ('N185', 8821), ('K297', 8629), ('S134', 8240), ('J0190', 7633), ('M501', 7217), ('Z_', 7169)], [('I109', 80308), ('J209', 73719), ('N_', 53832), ('F_', 53198), ('E119', 32049), ('K210', 20572), ('M511', 17773), ('M771', 16929), ('N185', 16815), ('L239', 16248), ('J304', 16094), ('J0390', 15939), ('S3350', 15920), ('M5456', 15760), ('J029', 13518), ('B_', 13512), ('J060', 13258), ('M5422', 13249), ('K219', 12718), ('D_', 12508), ('M750', 12254), ('M751', 12072), ('M501', 11996), ('C_', 11183), ('H0411', 11082), ('J00', 10313), ('J040', 9836), ('S134', 9734), ('K297', 9600), ('J40', 9506)], [('I109', 130126), ('J209', 67812), ('F_', 52255), ('N_', 51602), ('E119', 47820), ('K210', 24571), ('N185', 22571), ('M511', 22381), ('M750', 19390), ('L239', 18712), ('M5456', 18532), ('M771', 18139), ('M751', 17044), ('S3350', 16845), ('M501', 15253), ('J304', 14915), ('M170', 14845), ('M5422', 14767), ('K219', 14727), ('C_', 14022), ('J0390', 13772), ('B_', 13661), ('H0411', 13333), ('J029', 12743), ('J060', 12233), ('E785', 11052), ('J40', 10715), ('N300', 10622), ('B351', 10611), ('M4806', 10439)], [('I109', 189099), ('J209', 73525), ('E119', 66715), ('F_', 56418), ('N_', 37444), ('M170', 32599), ('N185', 31974), ('K210', 28056), ('M511', 27982), ('M5456', 22983), ('L239', 20955), ('M4806', 20602), ('M751', 20282), ('M750', 20215), ('S3350', 17384), ('K219', 17291), ('M501', 16325), ('E785', 15983), ('H0411', 15462), ('J304', 14637), ('M771', 14422), ('J0390', 14157), ('M171', 13929), ('C_', 13680), ('J029', 13464), ('M5422', 13459), ('J060', 12899), ('E118', 12867), ('B_', 12274), ('B351', 12203)], [('I109', 235201), ('E119', 77857), ('J209', 76631), ('F_', 62748), ('M170', 51882), ('M4806', 36599), ('N185', 34514), ('K210', 33447), ('M511', 31088), ('N_', 27082), ('M5456', 26544), ('M751', 22052), ('L239', 21436), ('M171', 20827), ('K219', 19521), ('M750', 19483), ('E785', 17902), ('N400', 17538), ('S3350', 17389), ('H0411', 16610), ('M501', 16400), ('E118', 15570), ('M179', 14791), ('J304', 13867), ('J40', 13626), ('J029', 12969), ('J0390', 12936), ('J060', 12623), ('C_', 12586), ('B351', 12308)], [('I109', 214517), ('E119', 67757), ('J209', 63102), ('M170', 60053), ('F_', 56135), ('M4806', 48061), ('N185', 36391), ('M5456', 28926), ('M511', 27860), ('K210', 26186), ('M171', 23201), ('N400', 20465), ('M751', 18302), ('L239', 18092), ('M750', 17095), ('K219', 16937), ('M179', 16624), ('H0411', 14592), ('S3350', 14207), ('N_', 13917), ('E118', 13709), ('E785', 13590), ('J40', 11955), ('M501', 11674), ('J304', 11115), ('J00', 10618), ('M5422', 10493), ('K297', 10346), ('J029', 10283), ('J060', 10207)], [('I109', 194597), ('F_', 59601), ('E119', 58231), ('M170', 56671), ('M4806', 55830), ('J209', 52696), ('N185', 39619), ('M5456', 31374), ('M511', 24575), ('N400', 24376), ('K210', 23477), ('M171', 20368), ('M179', 17011), ('L239', 16595), ('H0411', 14552), ('K219', 14253), ('E118', 13400), ('M751', 13189), ('M750', 12389), ('S3350', 11372), ('J40', 10878), ('M501', 10431), ('I639', 9919), ('J304', 9869), ('J00', 9562), ('E785', 9361), ('C_', 9326), ('I209', 9232), ('K297', 9229), ('N401', 8731)], [('I109', 177714), ('F_', 69903), ('M4806', 62135), ('M170', 49359), ('E119', 49223), ('J209', 43879), ('M5456', 34738), ('N185', 30377), ('M511', 21907), ('N400', 21310), ('K210', 18624), ('M171', 16903), ('M179', 16654), ('L239', 14362), ('H0411', 13406), ('I639', 12286), ('K219', 11821), ('E118', 11449), ('M750', 10117), ('M4807', 9515), ('J40', 9456), ('M751', 9406), ('J00', 9232), ('M5446', 8776), ('I209', 8754), ('C_', 8607), ('S3350', 8522), ('N401', 8055), ('G20', 8006), ('J304', 7927)], [('I109', 128016), ('F_', 70797), ('M4806', 42718), ('M170', 32286), ('E119', 29733), ('J209', 26915), ('M5456', 25448), ('N185', 22055), ('M511', 14004), ('N400', 12748), ('I639', 11557), ('M179', 11543), ('K210', 11237), ('M171', 10276), ('L239', 8537), ('H0411', 8468), ('G20', 7480), ('E118', 6830), ('M4807', 6715), ('K219', 6492), ('I209', 6422), ('J00', 6113), ('J40', 6026), ('M750', 5998), ('C_', 5655), ('N401', 5545), ('S3350', 5492), ('K297', 5400), ('J304', 5226), ('J459', 5121)]]

[[('J209', 453412), ('J304', 70540), ('J00', 52162), ('J029', 51109), ('J0190', 48636), ('J219', 44081), ('J0390', 39613), ('J069', 32555), ('J303', 29313), ('H66000', 28448), ('B_', 23642), ('J189', 22102), ('J0100', 20094), ('H6690', 19839), ('A090', 19426), ('J_', 19028), ('J060', 16024), ('A099', 15703), ('H6640', 13937), ('J459', 13314), ('J040', 11168), ('J329', 11113), ('R509', 9119), ('J40', 9003), ('J22', 8994), ('J320', 8862), ('J180', 8399), ('L209', 7446), ('J0180', 7001), ('L509', 6721)], [('J209', 285705), ('J304', 59793), ('J0190', 31899), ('J029', 31073), ('J0390', 30371), ('J_', 26700), ('J303', 26278), ('J00', 24248), ('J069', 15160), ('J0100', 14833), ('J060', 14593), ('J219', 14281), ('H101', 13424), ('A090', 13415), ('J040', 12733), ('A099', 12307), ('J329', 10733), ('H66000', 10688), ('H521', 10155), ('J459', 9836), ('J189', 9803), ('F_', 9140), ('J320', 8455), ('J40', 7836), ('B_', 7421), ('H6690', 6843), ('L239', 5694), ('J22', 5694), ('J0180', 5687), ('L209', 5638)], [('J209', 91515), ('J304', 24530), ('J0390', 15874), ('J029', 14845), ('H521', 14606), ('F_', 14424), ('J_', 14088), ('J303', 11766), ('J060', 9914), ('J0190', 9793), ('J00', 8799), ('H101', 8293), ('A099', 8125), ('A090', 7535), ('J040', 7427), ('B07', 6353), ('J069', 5391), ('L239', 5322), ('J329', 5045), ('J0100', 4990), ('E_', 4754), ('J40', 4556), ('L209', 4369), ('H5221', 4020), ('J320', 3774), ('E228', 3648), ('S9348', 3484), ('J219', 3353), ('H0001', 3107), ('H001', 3067)], [('J209', 58184), ('F_', 25224), ('J304', 14001), ('J0390', 13834), ('J029', 12773), ('J060', 10253), ('N_', 10075), ('A099', 9534), ('J00', 8541), ('J303', 7546), ('A090', 7366), ('L239', 6796), ('J040', 6510), ('H521', 6350), ('J_', 6222), ('J0190', 5885), ('K297', 5418), ('L209', 5349), ('K291', 5305), ('J40', 5296), ('J069', 5273), ('H101', 5212), ('S3350', 5036), ('K529', 4363), ('S9348', 4087), ('J329', 3677), ('K219', 3663), ('M5456', 3659), ('S9349', 3613), ('H001', 3592)], [('F_', 46897), ('J209', 42364), ('N_', 32992), ('J0390', 11645), ('L239', 10633), ('J304', 10063), ('J029', 9076), ('J060', 8208), ('A099', 8009), ('J00', 6645), ('B_', 6119), ('J040', 6081), ('K210', 5853), ('S3350', 5828), ('H0411', 5811), ('J303', 5740), ('H101', 5714), ('L209', 5671), ('K219', 5612), ('A090', 5547), ('A_', 5237), ('K297', 5160), ('J40', 5020), ('M5456', 4955), ('N300', 4702), ('K291', 4556), ('L238', 4401), ('M5422', 4278), ('J0190', 4180), ('J_', 4166)], [('N_', 53674), ('F_', 49983), ('J209', 49657), ('Z_', 16670), ('J0390', 14315), ('L239', 12206), ('J304', 11832), ('J029', 10505), ('J060', 10085), ('B_', 9847), ('A099', 9628), ('K210', 8828), ('S3350', 8494), ('M5422', 8260), ('J00', 8182), ('H0411', 7625), ('A_', 7625), ('M5456', 7532), ('K219', 7404), ('J040', 7315), ('O_', 7068), ('J303', 7022), ('J40', 6657), ('K297', 6647), ('N300', 6512), ('S134', 6432), ('A090', 6343), ('H101', 6166), ('K291', 5773), ('J_', 5444)], [('J209', 61782), ('N_', 55161), ('F_', 42333), ('Z_', 40906), ('O_', 18250), ('J0390', 15613), ('J304', 13287), ('J029', 12366), ('J060', 11420), ('L239', 10164), ('B_', 9514), ('K210', 9490), ('M5422', 9235), ('S3350', 9210), ('J00', 8945), ('J040', 8395), ('M5456', 8378), ('A099', 8069), ('J40', 7769), ('J303', 7526), ('M511', 7444), ('K219', 7373), ('S134', 6514), ('J0190', 6436), ('H0411', 6355), ('K297', 6322), ('A_', 6035), ('H101', 5603), ('N300', 5422), ('I109', 5371)], [('J209', 90301), ('N_', 56320), ('F_', 46723), ('Z_', 30426), ('J0390', 21270), ('J304', 18612), ('I109', 17066), ('J029', 16999), ('J060', 15495), ('O_', 14631), ('K210', 13313), ('S3350', 12697), ('L239', 12155), ('B_', 12129), ('J040', 11820), ('M5456', 11814), ('M511', 11417), ('M5422', 11350), ('J00', 11293), ('J40', 10743), ('J303', 10069), ('K219', 9712), ('J0190', 9616), ('E119', 9091), ('A099', 8264), ('S134', 7918), ('K297', 7794), ('H101', 7445), ('H0411', 7404), ('J_', 7146)], [('J209', 78969), ('N_', 51066), ('F_', 48614), ('I109', 38532), ('K210', 17802), ('J0390', 17631), ('J304', 17333), ('E119', 17140), ('M511', 14328), ('J029', 14320), ('J060', 14160), ('S3350', 13391), ('L239', 13135), ('M5456', 13017), ('B_', 12454), ('M5422', 11505), ('K219', 10885), ('J040', 10477), ('J00', 9922), ('J40', 9818), ('J303', 9531), ('M771', 9286), ('D_', 9201), ('H0411', 8883), ('N185', 8821), ('K297', 8629), ('S134', 8240), ('J0190', 7633), ('M501', 7217), ('Z_', 7169)], [('I109', 80308), ('J209', 73719), ('N_', 53832), ('F_', 53198), ('E119', 32049), ('K210', 20572), ('M511', 17773), ('M771', 16929), ('N185', 16815), ('L239', 16248), ('J304', 16094), ('J0390', 15939), ('S3350', 15920), ('M5456', 15760), ('J029', 13518), ('B_', 13512), ('J060', 13258), ('M5422', 13249), ('K219', 12718), ('D_', 12508), ('M750', 12254), ('M751', 12072), ('M501', 11996), ('C_', 11183), ('H0411', 11082), ('J00', 10313), ('J040', 9836), ('S134', 9734), ('K297', 9600), ('J40', 9506)], [('I109', 130126), ('J209', 67812), ('F_', 52255), ('N_', 51602), ('E119', 47820), ('K210', 24571), ('N185', 22571), ('M511', 22381), ('M750', 19390), ('L239', 18712), ('M5456', 18532), ('M771', 18139), ('M751', 17044), ('S3350', 16845), ('M501', 15253), ('J304', 14915), ('M170', 14845), ('M5422', 14767), ('K219', 14727), ('C_', 14022), ('J0390', 13772), ('B_', 13661), ('H0411', 13333), ('J029', 12743), ('J060', 12233), ('E785', 11052), ('J40', 10715), ('N300', 10622), ('B351', 10611), ('M4806', 10439)], [('I109', 189099), ('J209', 73525), ('E119', 66715), ('F_', 56418), ('N_', 37444), ('M170', 32599), ('N185', 31974), ('K210', 28056), ('M511', 27982), ('M5456', 22983), ('L239', 20955), ('M4806', 20602), ('M751', 20282), ('M750', 20215), ('S3350', 17384), ('K219', 17291), ('M501', 16325), ('E785', 15983), ('H0411', 15462), ('J304', 14637), ('M771', 14422), ('J0390', 14157), ('M171', 13929), ('C_', 13680), ('J029', 13464), ('M5422', 13459), ('J060', 12899), ('E118', 12867), ('B_', 12274), ('B351', 12203)], [('I109', 235201), ('E119', 77857), ('J209', 76631), ('F_', 62748), ('M170', 51882), ('M4806', 36599), ('N185', 34514), ('K210', 33447), ('M511', 31088), ('N_', 27082), ('M5456', 26544), ('M751', 22052), ('L239', 21436), ('M171', 20827), ('K219', 19521), ('M750', 19483), ('E785', 17902), ('N400', 17538), ('S3350', 17389), ('H0411', 16610), ('M501', 16400), ('E118', 15570), ('M179', 14791), ('J304', 13867), ('J40', 13626), ('J029', 12969), ('J0390', 12936), ('J060', 12623), ('C_', 12586), ('B351', 12308)], [('I109', 214517), ('E119', 67757), ('J209', 63102), ('M170', 60053), ('F_', 56135), ('M4806', 48061), ('N185', 36391), ('M5456', 28926), ('M511', 27860), ('K210', 26186), ('M171', 23201), ('N400', 20465), ('M751', 18302), ('L239', 18092), ('M750', 17095), ('K219', 16937), ('M179', 16624), ('H0411', 14592), ('S3350', 14207), ('N_', 13917), ('E118', 13709), ('E785', 13590), ('J40', 11955), ('M501', 11674), ('J304', 11115), ('J00', 10618), ('M5422', 10493), ('K297', 10346), ('J029', 10283), ('J060', 10207)], [('I109', 194597), ('F_', 59601), ('E119', 58231), ('M170', 56671), ('M4806', 55830), ('J209', 52696), ('N185', 39619), ('M5456', 31374), ('M511', 24575), ('N400', 24376), ('K210', 23477), ('M171', 20368), ('M179', 17011), ('L239', 16595), ('H0411', 14552), ('K219', 14253), ('E118', 13400), ('M751', 13189), ('M750', 12389), ('S3350', 11372), ('J40', 10878), ('M501', 10431), ('I639', 9919), ('J304', 9869), ('J00', 9562), ('E785', 9361), ('C_', 9326), ('I209', 9232), ('K297', 9229), ('N401', 8731)], [('I109', 177714), ('F_', 69903), ('M4806', 62135), ('M170', 49359), ('E119', 49223), ('J209', 43879), ('M5456', 34738), ('N185', 30377), ('M511', 21907), ('N400', 21310), ('K210', 18624), ('M171', 16903), ('M179', 16654), ('L239', 14362), ('H0411', 13406), ('I639', 12286), ('K219', 11821), ('E118', 11449), ('M750', 10117), ('M4807', 9515), ('J40', 9456), ('M751', 9406), ('J00', 9232), ('M5446', 8776), ('I209', 8754), ('C_', 8607), ('S3350', 8522), ('N401', 8055), ('G20', 8006), ('J304', 7927)], [('I109', 128016), ('F_', 70797), ('M4806', 42718), ('M170', 32286), ('E119', 29733), ('J209', 26915), ('M5456', 25448), ('N185', 22055), ('M511', 14004), ('N400', 12748), ('I639', 11557), ('M179', 11543), ('K210', 11237), ('M171', 10276), ('L239', 8537), ('H0411', 8468), ('G20', 7480), ('E118', 6830), ('M4807', 6715), ('K219', 6492), ('I209', 6422), ('J00', 6113), ('J40', 6026), ('M750', 5998), ('C_', 5655), ('N401', 5545), ('S3350', 5492), ('K297', 5400), ('J304', 5226), ('J459', 5121)], [('F_', 81133), ('I109', 78657), ('M4806', 18887), ('M170', 15329), ('E119', 13891), ('J209', 13484), ('M5456', 12156), ('N185', 9712), ('I639', 7809), ('N400', 6340), ('M179', 5569), ('M171', 5323), ('M511', 5224), ('G20', 5107), ('L239', 4627), ('K210', 4384), ('H0411', 4343), ('I209', 3587), ('C_', 3545), ('J40', 3535), ('J189', 3492), ('E118', 3401), ('J459', 3395), ('J00', 3352), ('M750', 3303), ('K219', 3208), ('I509', 3189), ('R42', 3019), ('K297', 2932), ('N401', 2757)]]

In [52]:
pd.DataFrame(list_d)[0].str.replace('(','')

C:\Users\Public\Documents\ESTsoft\CreatorTemp/ipykernel_6088/2649054760.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  pd.DataFrame(list_d)[0].str.replace('(','')

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
10   NaN
11   NaN
12   NaN
13   NaN
14   NaN
15   NaN
16   NaN
17   NaN
Name: 0, dtype: float64

In [22]:
pd.DataFrame(list_d)

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,"(J209, 453412)","(J304, 70540)","(J00, 52162)","(J029, 51109)","(J0190, 48636)","(J219, 44081)","(J0390, 39613)","(J069, 32555)","(J303, 29313)","(H66000, 28448)",...,"(J040, 11168)","(J329, 11113)","(R509, 9119)","(J40, 9003)","(J22, 8994)","(J320, 8862)","(J180, 8399)","(L209, 7446)","(J0180, 7001)","(L509, 6721)"
1,"(J209, 285705)","(J304, 59793)","(J0190, 31899)","(J029, 31073)","(J0390, 30371)","(J_, 26700)","(J303, 26278)","(J00, 24248)","(J069, 15160)","(J0100, 14833)",...,"(J189, 9803)","(F_, 9140)","(J320, 8455)","(J40, 7836)","(B_, 7421)","(H6690, 6843)","(L239, 5694)","(J22, 5694)","(J0180, 5687)","(L209, 5638)"
2,"(J209, 91515)","(J304, 24530)","(J0390, 15874)","(J029, 14845)","(H521, 14606)","(F_, 14424)","(J_, 14088)","(J303, 11766)","(J060, 9914)","(J0190, 9793)",...,"(E_, 4754)","(J40, 4556)","(L209, 4369)","(H5221, 4020)","(J320, 3774)","(E228, 3648)","(S9348, 3484)","(J219, 3353)","(H0001, 3107)","(H001, 3067)"
3,"(J209, 58184)","(F_, 25224)","(J304, 14001)","(J0390, 13834)","(J029, 12773)","(J060, 10253)","(N_, 10075)","(A099, 9534)","(J00, 8541)","(J303, 7546)",...,"(J069, 5273)","(H101, 5212)","(S3350, 5036)","(K529, 4363)","(S9348, 4087)","(J329, 3677)","(K219, 3663)","(M5456, 3659)","(S9349, 3613)","(H001, 3592)"
4,"(F_, 46897)","(J209, 42364)","(N_, 32992)","(J0390, 11645)","(L239, 10633)","(J304, 10063)","(J029, 9076)","(J060, 8208)","(A099, 8009)","(J00, 6645)",...,"(A_, 5237)","(K297, 5160)","(J40, 5020)","(M5456, 4955)","(N300, 4702)","(K291, 4556)","(L238, 4401)","(M5422, 4278)","(J0190, 4180)","(J_, 4166)"
5,"(N_, 53674)","(F_, 49983)","(J209, 49657)","(Z_, 16670)","(J0390, 14315)","(L239, 12206)","(J304, 11832)","(J029, 10505)","(J060, 10085)","(B_, 9847)",...,"(O_, 7068)","(J303, 7022)","(J40, 6657)","(K297, 6647)","(N300, 6512)","(S134, 6432)","(A090, 6343)","(H101, 6166)","(K291, 5773)","(J_, 5444)"
6,"(J209, 61782)","(N_, 55161)","(F_, 42333)","(Z_, 40906)","(O_, 18250)","(J0390, 15613)","(J304, 13287)","(J029, 12366)","(J060, 11420)","(L239, 10164)",...,"(M511, 7444)","(K219, 7373)","(S134, 6514)","(J0190, 6436)","(H0411, 6355)","(K297, 6322)","(A_, 6035)","(H101, 5603)","(N300, 5422)","(I109, 5371)"
7,"(J209, 90301)","(N_, 56320)","(F_, 46723)","(Z_, 30426)","(J0390, 21270)","(J304, 18612)","(I109, 17066)","(J029, 16999)","(J060, 15495)","(O_, 14631)",...,"(J303, 10069)","(K219, 9712)","(J0190, 9616)","(E119, 9091)","(A099, 8264)","(S134, 7918)","(K297, 7794)","(H101, 7445)","(H0411, 7404)","(J_, 7146)"
8,"(J209, 78969)","(N_, 51066)","(F_, 48614)","(I109, 38532)","(K210, 17802)","(J0390, 17631)","(J304, 17333)","(E119, 17140)","(M511, 14328)","(J029, 14320)",...,"(J303, 9531)","(M771, 9286)","(D_, 9201)","(H0411, 8883)","(N185, 8821)","(K297, 8629)","(S134, 8240)","(J0190, 7633)","(M501, 7217)","(Z_, 7169)"
9,"(I109, 80308)","(J209, 73719)","(N_, 53832)","(F_, 53198)","(E119, 32049)","(K210, 20572)","(M511, 17773)","(M771, 16929)","(N185, 16815)","(L239, 16248)",...,"(M750, 12254)","(M751, 12072)","(M501, 11996)","(C_, 11183)","(H0411, 11082)","(J00, 10313)","(J040, 9836)","(S134, 9734)","(K297, 9600)","(J40, 9506)"
10,"(I109, 130126)","(J209, 67812)","(F_, 52255)","(N_, 51602)","(E119, 47820)","(K210, 24571)","(N185, 22571)","(M511, 22381)","(M750, 19390)","(L239, 18712)",...,"(J0390, 13772)","(B_, 13661)","(H0411, 13333)","(J029, 12743)","(J060, 12233)","(E785, 11052)","(J40, 10715)","(N300, 10622)","(B351, 10611)","(M4806, 10439)"
11,"(I109, 189099)","(J209, 73525)","(E119, 66715)","(F_, 56418)","(N_, 37444)","(M170, 32599)","(N185, 31974)","(K210, 28056)","(M511, 27982)","(M5456, 22983)",...,"(M771, 14422)","(J0390, 14157)","(M171, 13929)","(C_, 13680)","(J029, 13464)","(M5422, 13459)","(J060, 12899)","(E118, 12867)","(B_, 12274)","(B351, 12203)"
12,"(I109, 235201)","(E119, 77857)","(J209, 76631)","(F_, 62748)","(M170, 51882)","(M4806, 36599)","(N185, 34514)","(K210, 33447)","(M511, 31088)","(N_, 27082)",...,"(M501, 16400)","(E118, 15570)","(M179, 14791)","(J304, 13867)","(J40, 13626)","(J029, 12969)","(J0390, 12936)","(J060, 12623)","(C_, 12586)","(B351, 12308)"
13,"(I109, 214517)","(E119, 67757)","(J209, 63102)","(M170, 60053)","(F_, 56135)","(M4806, 48061)","(N185, 36391)","(M5456, 28926)","(M511, 27860)","(K210, 26186)",...,"(E118, 13709)","(E785, 13590)","(J40, 11955)","(M501, 11674)","(J304, 11115)","(J00, 10618)","(M5422, 10493)","(K297, 10346)","(J029, 10283)","(J060, 10207)"
14,"(I109, 194597)","(F_, 59601)","(E119, 58231)","(M170, 56671)","(M4806, 55830)","(J209, 52696)","(N185, 39619)","(M5456, 31374)","(M511, 24575)","(N400, 24376)",...,"(J40, 10878)","(M501, 10431)","(I639, 9919)","(J304, 9869)","(J00, 9562)","(E785, 9361)","(C_, 9326)","(I209, 9232)","(K297, 9229)","(N401, 8731)"
15,"(I109, 177714)","(F_, 69903)","(M4806, 62135)","(M170, 49359)","(E119, 49223)","(J209, 43879)","(M5456, 34738)","(N185, 30377)","(M511, 21907)","(N400, 21310)",...,"(J40, 9456)","(M751, 9406)","(J00, 9232)","(M5446, 8776)","(I209, 8754)","(C_, 8607)","(S3350, 8522)","(N401, 8055)","(G20, 8006)","(J304, 7927)"
16,"(I109, 128016)","(F_, 70797)","(M4806, 42718)","(M170, 32286)","(E119, 29733)","(J209, 26915)","(M5456, 25448)","(N185, 22055)","(M511, 14004)","(N400, 12748)",...,"(I209, 6422)","(J00, 6113)","(J40, 6026)","(M750, 5998)","(C_, 5655)","(N401, 5545)","(S3350, 5492)","(K297, 5400)","(J304, 5226)","(J459, 5121)"
17,"(F_, 81133)","(I109, 78657)","(M4806, 18887)","(M170, 15329)","(E119, 13891)","(J209, 13484)","(M5456, 12156)","(N185, 9712)","(I639, 7809)","(N400, 6340)",...,"(J189, 3492)","(E118, 3401)","(J459, 3395)","(J00, 3352)","(M750, 3303)","(K219, 3208)","(I509, 3189)","(R42, 3019)","(K297, 2932)","(N401, 2757)"

In [42]:
ag1 = data_1920['연령대코드'] == 1
ag1s = data_1920[ag1]
ag1s_to = Counter(ag1s['주상병코드'])
ag1_1 = ag1s_to.most_common(30)
ag1_1

# list_d.append(aggs_to.most_common(30))

[('J209', 453412),
 ('J304', 70540),
 ('J00', 52162),
 ('J029', 51109),
 ('J0190', 48636),
 ('J219', 44081),
 ('J0390', 39613),
 ('J069', 32555),
 ('J303', 29313),
 ('H66000', 28448),
 ('B_', 23642),
 ('J189', 22102),
 ('J0100', 20094),
 ('H6690', 19839),
 ('A090', 19426),
 ('J_', 19028),
 ('J060', 16024),
 ('A099', 15703),
 ('H6640', 13937),
 ('J459', 13314),
 ('J040', 11168),
 ('J329', 11113),
 ('R509', 9119),
 ('J40', 9003),
 ('J22', 8994),
 ('J320', 8862),
 ('J180', 8399),
 ('L209', 7446),
 ('J0180', 7001),
 ('L509', 6721)]

In [44]:
ag2 = data_1920['연령대코드'] == 2
ag2s = data_1920[ag2]
ag2s_to = Counter(ag2s['주상병코드'])
ag2_2 = ag2s_to.most_common(30)
ag2_2

[('J209', 285705),
 ('J304', 59793),
 ('J0190', 31899),
 ('J029', 31073),
 ('J0390', 30371),
 ('J_', 26700),
 ('J303', 26278),
 ('J00', 24248),
 ('J069', 15160),
 ('J0100', 14833),
 ('J060', 14593),
 ('J219', 14281),
 ('H101', 13424),
 ('A090', 13415),
 ('J040', 12733),
 ('A099', 12307),
 ('J329', 10733),
 ('H66000', 10688),
 ('H521', 10155),
 ('J459', 9836),
 ('J189', 9803),
 ('F_', 9140),
 ('J320', 8455),
 ('J40', 7836),
 ('B_', 7421),
 ('H6690', 6843),
 ('L239', 5694),
 ('J22', 5694),
 ('J0180', 5687),
 ('L209', 5638)]

In [45]:
ag3 = data_1920['연령대코드'] == 3
ag3s = data_1920[ag3]
ag3s_to = Counter(ag3s['주상병코드'])
ag3_3 = ag3s_to.most_common(30)
ag3_3

[('J209', 91515),
 ('J304', 24530),
 ('J0390', 15874),
 ('J029', 14845),
 ('H521', 14606),
 ('F_', 14424),
 ('J_', 14088),
 ('J303', 11766),
 ('J060', 9914),
 ('J0190', 9793),
 ('J00', 8799),
 ('H101', 8293),
 ('A099', 8125),
 ('A090', 7535),
 ('J040', 7427),
 ('B07', 6353),
 ('J069', 5391),
 ('L239', 5322),
 ('J329', 5045),
 ('J0100', 4990),
 ('E_', 4754),
 ('J40', 4556),
 ('L209', 4369),
 ('H5221', 4020),
 ('J320', 3774),
 ('E228', 3648),
 ('S9348', 3484),
 ('J219', 3353),
 ('H0001', 3107),
 ('H001', 3067)]

In [55]:
ag4 = data_1920['연령대코드'] == 4
ag4s = data_1920[ag4]
ag4s_to = Counter(ag4s['주상병코드'])
ag4_4 = ag4s_to.most_common(30)
ag4_4

[('J209', 58184),
 ('F_', 25224),
 ('J304', 14001),
 ('J0390', 13834),
 ('J029', 12773),
 ('J060', 10253),
 ('N_', 10075),
 ('A099', 9534),
 ('J00', 8541),
 ('J303', 7546),
 ('A090', 7366),
 ('L239', 6796),
 ('J040', 6510),
 ('H521', 6350),
 ('J_', 6222),
 ('J0190', 5885),
 ('K297', 5418),
 ('L209', 5349),
 ('K291', 5305),
 ('J40', 5296),
 ('J069', 5273),
 ('H101', 5212),
 ('S3350', 5036),
 ('K529', 4363),
 ('S9348', 4087),
 ('J329', 3677),
 ('K219', 3663),
 ('M5456', 3659),
 ('S9349', 3613),
 ('H001', 3592)]

In [56]:
ag5 = data_1920['연령대코드'] == 5
ag5s = data_1920[ag5]
ag5s_to = Counter(ag5s['주상병코드'])
ag5_5 = ag5s_to.most_common(30)
ag5_5

[('F_', 46897),
 ('J209', 42364),
 ('N_', 32992),
 ('J0390', 11645),
 ('L239', 10633),
 ('J304', 10063),
 ('J029', 9076),
 ('J060', 8208),
 ('A099', 8009),
 ('J00', 6645),
 ('B_', 6119),
 ('J040', 6081),
 ('K210', 5853),
 ('S3350', 5828),
 ('H0411', 5811),
 ('J303', 5740),
 ('H101', 5714),
 ('L209', 5671),
 ('K219', 5612),
 ('A090', 5547),
 ('A_', 5237),
 ('K297', 5160),
 ('J40', 5020),
 ('M5456', 4955),
 ('N300', 4702),
 ('K291', 4556),
 ('L238', 4401),
 ('M5422', 4278),
 ('J0190', 4180),
 ('J_', 4166)]

In [57]:
ag6 = data_1920['연령대코드'] == 6
ag66 = data_1920[ag6]
ag666 = Counter(ag66['주상병코드'])
ag6666 = ag666.most_common(30)
ag6666

[('N_', 53674),
 ('F_', 49983),
 ('J209', 49657),
 ('Z_', 16670),
 ('J0390', 14315),
 ('L239', 12206),
 ('J304', 11832),
 ('J029', 10505),
 ('J060', 10085),
 ('B_', 9847),
 ('A099', 9628),
 ('K210', 8828),
 ('S3350', 8494),
 ('M5422', 8260),
 ('J00', 8182),
 ('H0411', 7625),
 ('A_', 7625),
 ('M5456', 7532),
 ('K219', 7404),
 ('J040', 7315),
 ('O_', 7068),
 ('J303', 7022),
 ('J40', 6657),
 ('K297', 6647),
 ('N300', 6512),
 ('S134', 6432),
 ('A090', 6343),
 ('H101', 6166),
 ('K291', 5773),
 ('J_', 5444)]

In [58]:
ag7 = data_1920['연령대코드'] == 7
ag77 = data_1920[ag7]
ag777 = Counter(ag77['주상병코드'])
ag7777 = ag777.most_common(30)
ag7777

[('J209', 61782),
 ('N_', 55161),
 ('F_', 42333),
 ('Z_', 40906),
 ('O_', 18250),
 ('J0390', 15613),
 ('J304', 13287),
 ('J029', 12366),
 ('J060', 11420),
 ('L239', 10164),
 ('B_', 9514),
 ('K210', 9490),
 ('M5422', 9235),
 ('S3350', 9210),
 ('J00', 8945),
 ('J040', 8395),
 ('M5456', 8378),
 ('A099', 8069),
 ('J40', 7769),
 ('J303', 7526),
 ('M511', 7444),
 ('K219', 7373),
 ('S134', 6514),
 ('J0190', 6436),
 ('H0411', 6355),
 ('K297', 6322),
 ('A_', 6035),
 ('H101', 5603),
 ('N300', 5422),
 ('I109', 5371)]

In [59]:
ag8 = data_1920['연령대코드'] == 8
ag88 = data_1920[ag8]
ag888 = Counter(ag88['주상병코드'])
ag8888 = ag888.most_common(30)
ag8888

[('J209', 90301),
 ('N_', 56320),
 ('F_', 46723),
 ('Z_', 30426),
 ('J0390', 21270),
 ('J304', 18612),
 ('I109', 17066),
 ('J029', 16999),
 ('J060', 15495),
 ('O_', 14631),
 ('K210', 13313),
 ('S3350', 12697),
 ('L239', 12155),
 ('B_', 12129),
 ('J040', 11820),
 ('M5456', 11814),
 ('M511', 11417),
 ('M5422', 11350),
 ('J00', 11293),
 ('J40', 10743),
 ('J303', 10069),
 ('K219', 9712),
 ('J0190', 9616),
 ('E119', 9091),
 ('A099', 8264),
 ('S134', 7918),
 ('K297', 7794),
 ('H101', 7445),
 ('H0411', 7404),
 ('J_', 7146)]

In [60]:
ag9 = data_1920['연령대코드'] == 9
ag99 = data_1920[ag9]
ag999 = Counter(ag66['주상병코드'])
ag9999 = ag999.most_common(30)
ag9999

[('N_', 53674),
 ('F_', 49983),
 ('J209', 49657),
 ('Z_', 16670),
 ('J0390', 14315),
 ('L239', 12206),
 ('J304', 11832),
 ('J029', 10505),
 ('J060', 10085),
 ('B_', 9847),
 ('A099', 9628),
 ('K210', 8828),
 ('S3350', 8494),
 ('M5422', 8260),
 ('J00', 8182),
 ('H0411', 7625),
 ('A_', 7625),
 ('M5456', 7532),
 ('K219', 7404),
 ('J040', 7315),
 ('O_', 7068),
 ('J303', 7022),
 ('J40', 6657),
 ('K297', 6647),
 ('N300', 6512),
 ('S134', 6432),
 ('A090', 6343),
 ('H101', 6166),
 ('K291', 5773),
 ('J_', 5444)]

In [61]:
ag10 = data_1920['연령대코드'] == 10
ag1010 = data_1920[ag10]
ag101010 = Counter(ag1010['주상병코드'])
ag10101010 = ag101010.most_common(30)
ag10101010

[('I109', 80308),
 ('J209', 73719),
 ('N_', 53832),
 ('F_', 53198),
 ('E119', 32049),
 ('K210', 20572),
 ('M511', 17773),
 ('M771', 16929),
 ('N185', 16815),
 ('L239', 16248),
 ('J304', 16094),
 ('J0390', 15939),
 ('S3350', 15920),
 ('M5456', 15760),
 ('J029', 13518),
 ('B_', 13512),
 ('J060', 13258),
 ('M5422', 13249),
 ('K219', 12718),
 ('D_', 12508),
 ('M750', 12254),
 ('M751', 12072),
 ('M501', 11996),
 ('C_', 11183),
 ('H0411', 11082),
 ('J00', 10313),
 ('J040', 9836),
 ('S134', 9734),
 ('K297', 9600),
 ('J40', 9506)]

In [62]:
agl1 = data_1920['연령대코드'] == 11
agl1l1 = data_1920[agl1]
agl1l1l1 = Counter(agl1l1['주상병코드'])
agl1l1l1l1 = agl1l1l1.most_common(30)
agl1l1l1l1

[('I109', 130126),
 ('J209', 67812),
 ('F_', 52255),
 ('N_', 51602),
 ('E119', 47820),
 ('K210', 24571),
 ('N185', 22571),
 ('M511', 22381),
 ('M750', 19390),
 ('L239', 18712),
 ('M5456', 18532),
 ('M771', 18139),
 ('M751', 17044),
 ('S3350', 16845),
 ('M501', 15253),
 ('J304', 14915),
 ('M170', 14845),
 ('M5422', 14767),
 ('K219', 14727),
 ('C_', 14022),
 ('J0390', 13772),
 ('B_', 13661),
 ('H0411', 13333),
 ('J029', 12743),
 ('J060', 12233),
 ('E785', 11052),
 ('J40', 10715),
 ('N300', 10622),
 ('B351', 10611),
 ('M4806', 10439)]

In [63]:
ag12 = data_1920['연령대코드'] == 12
agq = data_1920[ag12]
agqq = Counter(agq['주상병코드'])
agqqq = agqq.most_common(30)
agqqq

[('I109', 189099),
 ('J209', 73525),
 ('E119', 66715),
 ('F_', 56418),
 ('N_', 37444),
 ('M170', 32599),
 ('N185', 31974),
 ('K210', 28056),
 ('M511', 27982),
 ('M5456', 22983),
 ('L239', 20955),
 ('M4806', 20602),
 ('M751', 20282),
 ('M750', 20215),
 ('S3350', 17384),
 ('K219', 17291),
 ('M501', 16325),
 ('E785', 15983),
 ('H0411', 15462),
 ('J304', 14637),
 ('M771', 14422),
 ('J0390', 14157),
 ('M171', 13929),
 ('C_', 13680),
 ('J029', 13464),
 ('M5422', 13459),
 ('J060', 12899),
 ('E118', 12867),
 ('B_', 12274),
 ('B351', 12203)]

In [64]:
ag13 = data_1920['연령대코드'] == 13
agy = data_1920[ag13]
agyy = Counter(agy['주상병코드'])
agyyy = agyy.most_common(30)
agyyy

[('I109', 235201),
 ('E119', 77857),
 ('J209', 76631),
 ('F_', 62748),
 ('M170', 51882),
 ('M4806', 36599),
 ('N185', 34514),
 ('K210', 33447),
 ('M511', 31088),
 ('N_', 27082),
 ('M5456', 26544),
 ('M751', 22052),
 ('L239', 21436),
 ('M171', 20827),
 ('K219', 19521),
 ('M750', 19483),
 ('E785', 17902),
 ('N400', 17538),
 ('S3350', 17389),
 ('H0411', 16610),
 ('M501', 16400),
 ('E118', 15570),
 ('M179', 14791),
 ('J304', 13867),
 ('J40', 13626),
 ('J029', 12969),
 ('J0390', 12936),
 ('J060', 12623),
 ('C_', 12586),
 ('B351', 12308)]

In [65]:
ag14 = data_1920['연령대코드'] == 14
agb = data_1920[ag14]
agbb = Counter(agb['주상병코드'])
agbbb = agbb.most_common(30)
agbbb

[('I109', 214517),
 ('E119', 67757),
 ('J209', 63102),
 ('M170', 60053),
 ('F_', 56135),
 ('M4806', 48061),
 ('N185', 36391),
 ('M5456', 28926),
 ('M511', 27860),
 ('K210', 26186),
 ('M171', 23201),
 ('N400', 20465),
 ('M751', 18302),
 ('L239', 18092),
 ('M750', 17095),
 ('K219', 16937),
 ('M179', 16624),
 ('H0411', 14592),
 ('S3350', 14207),
 ('N_', 13917),
 ('E118', 13709),
 ('E785', 13590),
 ('J40', 11955),
 ('M501', 11674),
 ('J304', 11115),
 ('J00', 10618),
 ('M5422', 10493),
 ('K297', 10346),
 ('J029', 10283),
 ('J060', 10207)]

In [66]:
ag15 = data_1920['연령대코드'] == 15
agv = data_1920[ag15]
agvv = Counter(agv['주상병코드'])
agvvv = agvv.most_common(30)
agvvv

[('I109', 194597),
 ('F_', 59601),
 ('E119', 58231),
 ('M170', 56671),
 ('M4806', 55830),
 ('J209', 52696),
 ('N185', 39619),
 ('M5456', 31374),
 ('M511', 24575),
 ('N400', 24376),
 ('K210', 23477),
 ('M171', 20368),
 ('M179', 17011),
 ('L239', 16595),
 ('H0411', 14552),
 ('K219', 14253),
 ('E118', 13400),
 ('M751', 13189),
 ('M750', 12389),
 ('S3350', 11372),
 ('J40', 10878),
 ('M501', 10431),
 ('I639', 9919),
 ('J304', 9869),
 ('J00', 9562),
 ('E785', 9361),
 ('C_', 9326),
 ('I209', 9232),
 ('K297', 9229),
 ('N401', 8731)]

In [67]:
ag16 = data_1920['연령대코드'] == 16
agh = data_1920[ag16]
aghh = Counter(agh['주상병코드'])
aghhh = aghh.most_common(30)
aghhh

[('I109', 177714),
 ('F_', 69903),
 ('M4806', 62135),
 ('M170', 49359),
 ('E119', 49223),
 ('J209', 43879),
 ('M5456', 34738),
 ('N185', 30377),
 ('M511', 21907),
 ('N400', 21310),
 ('K210', 18624),
 ('M171', 16903),
 ('M179', 16654),
 ('L239', 14362),
 ('H0411', 13406),
 ('I639', 12286),
 ('K219', 11821),
 ('E118', 11449),
 ('M750', 10117),
 ('M4807', 9515),
 ('J40', 9456),
 ('M751', 9406),
 ('J00', 9232),
 ('M5446', 8776),
 ('I209', 8754),
 ('C_', 8607),
 ('S3350', 8522),
 ('N401', 8055),
 ('G20', 8006),
 ('J304', 7927)]

In [74]:
ag17 = data_1920['연령대코드'] == 17
agm = data_1920[ag17]
agmm = Counter(agm['주상병코드'])
agmmm = agmm.most_common(30)
agmmm

[('I109', 128016),
 ('F_', 70797),
 ('M4806', 42718),
 ('M170', 32286),
 ('E119', 29733),
 ('J209', 26915),
 ('M5456', 25448),
 ('N185', 22055),
 ('M511', 14004),
 ('N400', 12748),
 ('I639', 11557),
 ('M179', 11543),
 ('K210', 11237),
 ('M171', 10276),
 ('L239', 8537),
 ('H0411', 8468),
 ('G20', 7480),
 ('E118', 6830),
 ('M4807', 6715),
 ('K219', 6492),
 ('I209', 6422),
 ('J00', 6113),
 ('J40', 6026),
 ('M750', 5998),
 ('C_', 5655),
 ('N401', 5545),
 ('S3350', 5492),
 ('K297', 5400),
 ('J304', 5226),
 ('J459', 5121)]

In [68]:
ag18 = data_1920['연령대코드'] == 18
agf = data_1920[ag18]
agff = Counter(agf['주상병코드'])
agfff = agff.most_common(30)
agfff

[('F_', 81133),
 ('I109', 78657),
 ('M4806', 18887),
 ('M170', 15329),
 ('E119', 13891),
 ('J209', 13484),
 ('M5456', 12156),
 ('N185', 9712),
 ('I639', 7809),
 ('N400', 6340),
 ('M179', 5569),
 ('M171', 5323),
 ('M511', 5224),
 ('G20', 5107),
 ('L239', 4627),
 ('K210', 4384),
 ('H0411', 4343),
 ('I209', 3587),
 ('C_', 3545),
 ('J40', 3535),
 ('J189', 3492),
 ('E118', 3401),
 ('J459', 3395),
 ('J00', 3352),
 ('M750', 3303),
 ('K219', 3208),
 ('I509', 3189),
 ('R42', 3019),
 ('K297', 2932),
 ('N401', 2757)]

In [53]:
ag1_1_df = pd.DataFrame(ag1_1)
a1 = ag1_1_df[0]
a1

0       J209
1       J304
2        J00
3       J029
4      J0190
5       J219
6      J0390
7       J069
8       J303
9     H66000
10        B_
11      J189
12     J0100
13     H6690
14      A090
15        J_
16      J060
17      A099
18     H6640
19      J459
20      J040
21      J329
22      R509
23       J40
24       J22
25      J320
26      J180
27      L209
28     J0180
29      L509
Name: 0, dtype: object

In [69]:
ag2_2_df = pd.DataFrame(ag2_2)
a2 = ag2_2_df[0]
a2

0       J209
1       J304
2      J0190
3       J029
4      J0390
5         J_
6       J303
7        J00
8       J069
9      J0100
10      J060
11      J219
12      H101
13      A090
14      J040
15      A099
16      J329
17    H66000
18      H521
19      J459
20      J189
21        F_
22      J320
23       J40
24        B_
25     H6690
26      L239
27       J22
28     J0180
29      L209
Name: 0, dtype: object

In [70]:
ag3_3_df = pd.DataFrame(ag3_3)
a3 = ag3_3_df[0]
a3

0      J209
1      J304
2     J0390
3      J029
4      H521
5        F_
6        J_
7      J303
8      J060
9     J0190
10      J00
11     H101
12     A099
13     A090
14     J040
15      B07
16     J069
17     L239
18     J329
19    J0100
20       E_
21      J40
22     L209
23    H5221
24     J320
25     E228
26    S9348
27     J219
28    H0001
29     H001
Name: 0, dtype: object

In [71]:
ag4_4_df = pd.DataFrame(ag4_4)
a4 = ag4_4_df[0]
a4

0      J209
1        F_
2      J304
3     J0390
4      J029
5      J060
6        N_
7      A099
8       J00
9      J303
10     A090
11     L239
12     J040
13     H521
14       J_
15    J0190
16     K297
17     L209
18     K291
19      J40
20     J069
21     H101
22    S3350
23     K529
24    S9348
25     J329
26     K219
27    M5456
28    S9349
29     H001
Name: 0, dtype: object

In [72]:
ag5_5_df = pd.DataFrame(ag5_5)
a5 = ag5_5_df[0]
a5

0        F_
1      J209
2        N_
3     J0390
4      L239
5      J304
6      J029
7      J060
8      A099
9       J00
10       B_
11     J040
12     K210
13    S3350
14    H0411
15     J303
16     H101
17     L209
18     K219
19     A090
20       A_
21     K297
22      J40
23    M5456
24     N300
25     K291
26     L238
27    M5422
28    J0190
29       J_
Name: 0, dtype: object

In [73]:
ag6666_df = pd.DataFrame(ag6666)
a6 = ag6666_df[0]
a6

0        N_
1        F_
2      J209
3        Z_
4     J0390
5      L239
6      J304
7      J029
8      J060
9        B_
10     A099
11     K210
12    S3350
13    M5422
14      J00
15    H0411
16       A_
17    M5456
18     K219
19     J040
20       O_
21     J303
22      J40
23     K297
24     N300
25     S134
26     A090
27     H101
28     K291
29       J_
Name: 0, dtype: object

In [75]:
ag7777_df = pd.DataFrame(ag7777)
a7 = ag7777_df[0]
a7

0      J209
1        N_
2        F_
3        Z_
4        O_
5     J0390
6      J304
7      J029
8      J060
9      L239
10       B_
11     K210
12    M5422
13    S3350
14      J00
15     J040
16    M5456
17     A099
18      J40
19     J303
20     M511
21     K219
22     S134
23    J0190
24    H0411
25     K297
26       A_
27     H101
28     N300
29     I109
Name: 0, dtype: object

In [77]:
ag8888_df = pd.DataFrame(ag8888)
a8 = ag8888_df[0]
a8

0      J209
1        N_
2        F_
3        Z_
4     J0390
5      J304
6      I109
7      J029
8      J060
9        O_
10     K210
11    S3350
12     L239
13       B_
14     J040
15    M5456
16     M511
17    M5422
18      J00
19      J40
20     J303
21     K219
22    J0190
23     E119
24     A099
25     S134
26     K297
27     H101
28    H0411
29       J_
Name: 0, dtype: object

In [78]:
ag9999_df = pd.DataFrame(ag9999)
a9 = ag9999_df[0]
a9

0        N_
1        F_
2      J209
3        Z_
4     J0390
5      L239
6      J304
7      J029
8      J060
9        B_
10     A099
11     K210
12    S3350
13    M5422
14      J00
15    H0411
16       A_
17    M5456
18     K219
19     J040
20       O_
21     J303
22      J40
23     K297
24     N300
25     S134
26     A090
27     H101
28     K291
29       J_
Name: 0, dtype: object

In [79]:
ag10101010_df = pd.DataFrame(ag10101010)
a10 = ag10101010_df[0]
a10

0      I109
1      J209
2        N_
3        F_
4      E119
5      K210
6      M511
7      M771
8      N185
9      L239
10     J304
11    J0390
12    S3350
13    M5456
14     J029
15       B_
16     J060
17    M5422
18     K219
19       D_
20     M750
21     M751
22     M501
23       C_
24    H0411
25      J00
26     J040
27     S134
28     K297
29      J40
Name: 0, dtype: object

In [80]:
agl1l1l1l1_df = pd.DataFrame(agl1l1l1l1)
a11 = agl1l1l1l1_df[0]
a11

0      I109
1      J209
2        F_
3        N_
4      E119
5      K210
6      N185
7      M511
8      M750
9      L239
10    M5456
11     M771
12     M751
13    S3350
14     M501
15     J304
16     M170
17    M5422
18     K219
19       C_
20    J0390
21       B_
22    H0411
23     J029
24     J060
25     E785
26      J40
27     N300
28     B351
29    M4806
Name: 0, dtype: object

In [81]:
agqqq_df = pd.DataFrame(agqqq)
a12 = agqqq_df[0]
a12

0      I109
1      J209
2      E119
3        F_
4        N_
5      M170
6      N185
7      K210
8      M511
9     M5456
10     L239
11    M4806
12     M751
13     M750
14    S3350
15     K219
16     M501
17     E785
18    H0411
19     J304
20     M771
21    J0390
22     M171
23       C_
24     J029
25    M5422
26     J060
27     E118
28       B_
29     B351
Name: 0, dtype: object

In [82]:
agyyy_df = pd.DataFrame(agyyy)
a13 = agyyy_df[0]
a13

0      I109
1      E119
2      J209
3        F_
4      M170
5     M4806
6      N185
7      K210
8      M511
9        N_
10    M5456
11     M751
12     L239
13     M171
14     K219
15     M750
16     E785
17     N400
18    S3350
19    H0411
20     M501
21     E118
22     M179
23     J304
24      J40
25     J029
26    J0390
27     J060
28       C_
29     B351
Name: 0, dtype: object

In [83]:
agbbb_df = pd.DataFrame(agbbb)
a14 = agbbb_df[0]
a14

0      I109
1      E119
2      J209
3      M170
4        F_
5     M4806
6      N185
7     M5456
8      M511
9      K210
10     M171
11     N400
12     M751
13     L239
14     M750
15     K219
16     M179
17    H0411
18    S3350
19       N_
20     E118
21     E785
22      J40
23     M501
24     J304
25      J00
26    M5422
27     K297
28     J029
29     J060
Name: 0, dtype: object

In [84]:
agvvv_df = pd.DataFrame(agvvv)
a15 = agvvv_df[0]
a15

0      I109
1        F_
2      E119
3      M170
4     M4806
5      J209
6      N185
7     M5456
8      M511
9      N400
10     K210
11     M171
12     M179
13     L239
14    H0411
15     K219
16     E118
17     M751
18     M750
19    S3350
20      J40
21     M501
22     I639
23     J304
24      J00
25     E785
26       C_
27     I209
28     K297
29     N401
Name: 0, dtype: object

In [85]:
aghhh_df = pd.DataFrame(aghhh)
a16 = aghhh_df[0]
a16

0      I109
1        F_
2     M4806
3      M170
4      E119
5      J209
6     M5456
7      N185
8      M511
9      N400
10     K210
11     M171
12     M179
13     L239
14    H0411
15     I639
16     K219
17     E118
18     M750
19    M4807
20      J40
21     M751
22      J00
23    M5446
24     I209
25       C_
26    S3350
27     N401
28      G20
29     J304
Name: 0, dtype: object

In [86]:
agmmm_df = pd.DataFrame(agmmm)
a17 = agmmm_df[0]
a17

0      I109
1        F_
2     M4806
3      M170
4      E119
5      J209
6     M5456
7      N185
8      M511
9      N400
10     I639
11     M179
12     K210
13     M171
14     L239
15    H0411
16      G20
17     E118
18    M4807
19     K219
20     I209
21      J00
22      J40
23     M750
24       C_
25     N401
26    S3350
27     K297
28     J304
29     J459
Name: 0, dtype: object

In [87]:
agfff_df = pd.DataFrame(agfff)
a18 = agfff_df[0]
a18

0        F_
1      I109
2     M4806
3      M170
4      E119
5      J209
6     M5456
7      N185
8      I639
9      N400
10     M179
11     M171
12     M511
13      G20
14     L239
15     K210
16    H0411
17     I209
18       C_
19      J40
20     J189
21     E118
22     J459
23      J00
24     M750
25     K219
26     I509
27      R42
28     K297
29     N401
Name: 0, dtype: object

In [96]:
da1 = pd.DataFrame([a1])
da2 = pd.DataFrame([a2]) 
da3 = pd.DataFrame([a3]) 
da4 = pd.DataFrame([a4]) 
da5 = pd.DataFrame([a5]) 
da6 = pd.DataFrame([a6]) 
da7 = pd.DataFrame([a7]) 
da8 = pd.DataFrame([a8]) 
da9 = pd.DataFrame([a9]) 
da10 = pd.DataFrame([a10]) 
da11 = pd.DataFrame([a11]) 
da12 = pd.DataFrame([a12]) 
da13 = pd.DataFrame([a13]) 
da14 = pd.DataFrame([a14]) 
da15 = pd.DataFrame([a15]) 
da16 = pd.DataFrame([a16])
da17 = pd.DataFrame([a17])
da18 = pd.DataFrame([a18])

In [97]:
daad = pd.concat([da1,da2,da3,da4,da5,da6,da7,da8,da9,da10,da11,da12,da13,da14,da15,da16,da17,da18])
daad

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,J209,J304,J00,J029,J0190,J219,J0390,J069,J303,H66000,...,J040,J329,R509,J40,J22,J320,J180,L209,J0180,L509
0,J209,J304,J0190,J029,J0390,J_,J303,J00,J069,J0100,...,J189,F_,J320,J40,B_,H6690,L239,J22,J0180,L209
0,J209,J304,J0390,J029,H521,F_,J_,J303,J060,J0190,...,E_,J40,L209,H5221,J320,E228,S9348,J219,H0001,H001
0,J209,F_,J304,J0390,J029,J060,N_,A099,J00,J303,...,J069,H101,S3350,K529,S9348,J329,K219,M5456,S9349,H001
0,F_,J209,N_,J0390,L239,J304,J029,J060,A099,J00,...,A_,K297,J40,M5456,N300,K291,L238,M5422,J0190,J_
0,N_,F_,J209,Z_,J0390,L239,J304,J029,J060,B_,...,O_,J303,J40,K297,N300,S134,A090,H101,K291,J_
0,J209,N_,F_,Z_,O_,J0390,J304,J029,J060,L239,...,M511,K219,S134,J0190,H0411,K297,A_,H101,N300,I109
0,J209,N_,F_,Z_,J0390,J304,I109,J029,J060,O_,...,J303,K219,J0190,E119,A099,S134,K297,H101,H0411,J_
0,N_,F_,J209,Z_,J0390,L239,J304,J029,J060,B_,...,O_,J303,J40,K297,N300,S134,A090,H101,K291,J_
0,I109,J209,N_,F_,E119,K210,M511,M771,N185,L239,...,M750,M751,M501,C_,H0411,J00,J040,S134,K297,J40
0,I109,J209,F_,N_,E119,K210,N185,M511,M750,L239,...,J0390,B_,H0411,J029,J060,E785,J40,N300,B351,M4806
0,I109,J209,E119,F_,N_,M170,N185,K210,M511,M5456,...,M771,J0390,M171,C_,J029,M5422,J060,E118,B_,B351
0,I109,E119,J209,F_,M170,M4806,N185,K210,M511,N_,...,M501,E118,M179,J304,J40,J029,J0390,J060,C_,B351
0,I109,E119,J209,M170,F_,M4806,N185,M5456,M511,K210,...,E118,E785,J40,M501,J304,J00,M5422,K297,J029,J060
0,I109,F_,E119,M170,M4806,J209,N185,M5456,M511,N400,...,J40,M501,I639,J304,J00,E785,C_,I209,K297,N401
0,I109,F_,M4806,M170,E119,J209,M5456,N185,M511,N400,...,J40,M751,J00,M5446,I209,C_,S3350,N401,G20,J304
0,I109,F_,M4806,M170,E119,J209,M5456,N185,M511,N400,...,I209,J00,J40,M750,C_,N401,S3350,K297,J304,J459
0,F_,I109,M4806,M170,E119,J209,M5456,N185,I639,N400,...,J189,E118,J459,J00,M750,K219,I509,R42,K297,N401

In [121]:
dada.unique()

array(['J209', 'F_', 'N_', 'I109', 'J304', 'E119', 'J00', 'J0190',
       'J0390', 'M4806', 'J029', 'Z_', 'M170', 'H521', 'L239', 'O_',
       'J219', 'J_', 'J060', 'K210', 'J303', 'M511', 'N185', 'M5456',
       'J069', 'A099', 'M771', 'M750', 'I639', 'H66000', 'J0100', 'B_',
       'N400', 'A090', 'M171', 'M179', 'J189', 'H101', 'J040', 'S3350',
       'M751', 'M5422', 'H6690', 'G20', 'H0411', 'M501', 'K219', 'B07',
       'J329', 'K297', 'A_', 'E785', 'E118', 'L209', 'I209', 'H6640',
       'K291', 'J40', 'M4807', 'C_', 'J459', 'D_', 'E_', 'R509', 'J320',
       'S134', 'H5221', 'K529', 'M5446', 'J22', 'S9348', 'N300', 'E228',
       'N401', 'J180', 'L238', 'I509', 'R42', 'J0180', 'H0001', 'S9349',
       'B351', 'L509', 'H001'], dtype=object)

In [104]:
dada = daad.unstack()
wls_vc = dada.value_counts()
wls_vc

J209     18
J40      17
F_       17
J304     17
L239     17
         ..
D_        1
E_        1
M5446     1
K529      1
J180      1
Length: 84, dtype: int64

In [118]:
wls_vc.unique()

array([18, 17, 15, 14, 13, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1],
      dtype=int64)

In [100]:
daad.value_counts()

0     1     2      3      4      5      6      7      8     9       10     11     12     13     14     15     16     17      18     19     20     21     22     23     24     25     26     27     28     29
N_    F_    J209   Z_     J0390  L239   J304   J029   J060  B_      A099   K210   S3350  M5422  J00    H0411  A_     M5456   K219   J040   O_     J303   J40    K297   N300   S134   A090   H101   K291   J_       2
I109  J209  N_     F_     E119   K210   M511   M771   N185  L239    J304   J0390  S3350  M5456  J029   B_     J060   M5422   K219   D_     M750   M751   M501   C_     H0411  J00    J040   S134   K297   J40      1
J209  N_    F_     Z_     O_     J0390  J304   J029   J060  L239    B_     K210   M5422  S3350  J00    J040   M5456  A099    J40    J303   M511   K219   S134   J0190  H0411  K297   A_     H101   N300   I109     1
                          J0390  J304   I109   J029   J060  O_      K210   S3350  L239   B_     J040   M5456  M511   M5422   J00    J40    J303   K219   J0190  E119   A099   S134   K297   H101   H0411  J_       1
      J304  J0390  J029   H521   F_     J_     J303   J060  J0190   J00    H101   A099   A090   J040   B07    J069   L239    J329   J0100  E_     J40    L209   H5221  J320   E228   S9348  J219   H0001  H001     1
            J0190  J029   J0390  J_     J303   J00    J069  J0100   J060   J219   H101   A090   J040   A099   J329   H66000  H521   J459   J189   F_     J320   J40    B_     H6690  L239   J22    J0180  L209     1
            J00    J029   J0190  J219   J0390  J069   J303  H66000  B_     J189   J0100  H6690  A090   J_     J060   A099    H6640  J459   J040   J329   R509   J40    J22    J320   J180   L209   J0180  L509     1
      F_    J304   J0390  J029   J060   N_     A099   J00   J303    A090   L239   J040   H521   J_     J0190  K297   L209    K291   J40    J069   H101   S3350  K529   S9348  J329   K219   M5456  S9349  H001     1
F_    I109  M4806  M170   E119   J209   M5456  N185   I639  N400    M179   M171   M511   G20    L239   K210   H0411  I209    C_     J40    J189   E118   J459   J00    M750   K219   I509   R42    K297   N401     1
      J209  N_     J0390  L239   J304   J029   J060   A099  J00     B_     J040   K210   S3350  H0411  J303   H101   L209    K219   A090   A_     K297   J40    M5456  N300   K291   L238   M5422  J0190  J_       1
I109  J209  E119   F_     N_     M170   N185   K210   M511  M5456   L239   M4806  M751   M750   S3350  K219   M501   E785    H0411  J304   M771   J0390  M171   C_     J029   M5422  J060   E118   B_     B351     1
      F_    M4806  M170   E119   J209   M5456  N185   M511  N400    K210   M171   M179   L239   H0411  I639   K219   E118    M750   M4807  J40    M751   J00    M5446  I209   C_     S3350  N401   G20    J304     1
                                                                    I639   M179   K210   M171   L239   H0411  G20    E118    M4807  K219   I209   J00    J40    M750   C_     N401   S3350  K297   J304   J459     1
            E119   M170   M4806  J209   N185   M5456  M511  N400    K210   M171   M179   L239   H0411  K219   E118   M751    M750   S3350  J40    M501   I639   J304   J00    E785   C_     I209   K297   N401     1
      E119  J209   M170   F_     M4806  N185   M5456  M511  K210    M171   N400   M751   L239   M750   K219   M179   H0411   S3350  N_     E118   E785   J40    M501   J304   J00    M5422  K297   J029   J060     1
                   F_     M170   M4806  N185   K210   M511  N_      M5456  M751   L239   M171   K219   M750   E785   N400    S3350  H0411  M501   E118   M179   J304   J40    J029   J0390  J060   C_     B351     1
      J209  F_     N_     E119   K210   N185   M511   M750  L239    M5456  M771   M751   S3350  M501   J304   M170   M5422   K219   C_     J0390  B_     H0411  J029   J060   E785   J40    N300   B351   M4806    1
dtype: int64

In [113]:
wls_vcd = pd.DataFrame(wls_vc, index)
wls_vcd.sort_index()

        0
A090    7
A099    9
A_      4
B07     1
B351    3
...    ..
S134    5
S3350  14
S9348   2
S9349   1
Z_      4

[84 rows x 1 columns]

In [135]:
illness = wls_vcd.reset_index(drop=False)
illness

    index   0
0    J209  18
1     J40  17
2      F_  17
3    J304  17
4    L239  17
..    ...  ..
79     D_   1
80     E_   1
81  M5446   1
82   K529   1
83   J180   1

[84 rows x 2 columns]

In [138]:
illness.index.name = '순위'
illness

    index   0
순위
0    J209  18
1     J40  17
2      F_  17
3    J304  17
4    L239  17
..    ...  ..
79     D_   1
80     E_   1
81  M5446   1
82   K529   1
83   J180   1

[84 rows x 2 columns]

In [139]:
illness.columns

Index(['index', 0], dtype='object')

In [140]:
illness.columns = ['질병코드', '빈도수']
illness

     질병코드  빈도수
순위
0    J209   18
1     J40   17
2      F_   17
3    J304   17
4    L239   17
..    ...  ...
79     D_    1
80     E_    1
81  M5446    1
82   K529    1
83   J180    1

[84 rows x 2 columns]

In [144]:
illness.to_excel('./data/illness.xlsx')

In [145]:
from wordcloud import WordCloud
from matplotlib import rc, font_manager

In [146]:
path = 'c:/Windows/Fonts/malgun.ttf'
font_name = font_manager.FontProperties(fname = path).get_name()
font_name
rc('font', family = font_name)

In [156]:
wordcloud=WordCloud(font_path= font_name, 
                    background_color="white",
                    max_words=100,
                    relative_scaling= 0.3,
                    width = 800,
                    height = 400
                 ).generate_from_frequencies(list_t)  
plt.figure(figsize=(15,10))
plt.imshow(wordcloud)
plt.axis('off')
plt.show()

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [150]:
plt.figure(figsize = (10,8))
sns.barplot(x = 'counts', y = 'tags',
           data = list_d)
plt.show()

AttributeError: 'list' object has no attribute 'get'

In [ ]:
illness.to_excel('./data/illness.xlsx')

In [155]:
list_t = pd.DataFrame(list_d)
list_t

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,"(J209, 453412)","(J304, 70540)","(J00, 52162)","(J029, 51109)","(J0190, 48636)","(J219, 44081)","(J0390, 39613)","(J069, 32555)","(J303, 29313)","(H66000, 28448)",...,"(J040, 11168)","(J329, 11113)","(R509, 9119)","(J40, 9003)","(J22, 8994)","(J320, 8862)","(J180, 8399)","(L209, 7446)","(J0180, 7001)","(L509, 6721)"
1,"(J209, 285705)","(J304, 59793)","(J0190, 31899)","(J029, 31073)","(J0390, 30371)","(J_, 26700)","(J303, 26278)","(J00, 24248)","(J069, 15160)","(J0100, 14833)",...,"(J189, 9803)","(F_, 9140)","(J320, 8455)","(J40, 7836)","(B_, 7421)","(H6690, 6843)","(L239, 5694)","(J22, 5694)","(J0180, 5687)","(L209, 5638)"
2,"(J209, 91515)","(J304, 24530)","(J0390, 15874)","(J029, 14845)","(H521, 14606)","(F_, 14424)","(J_, 14088)","(J303, 11766)","(J060, 9914)","(J0190, 9793)",...,"(E_, 4754)","(J40, 4556)","(L209, 4369)","(H5221, 4020)","(J320, 3774)","(E228, 3648)","(S9348, 3484)","(J219, 3353)","(H0001, 3107)","(H001, 3067)"
3,"(J209, 58184)","(F_, 25224)","(J304, 14001)","(J0390, 13834)","(J029, 12773)","(J060, 10253)","(N_, 10075)","(A099, 9534)","(J00, 8541)","(J303, 7546)",...,"(J069, 5273)","(H101, 5212)","(S3350, 5036)","(K529, 4363)","(S9348, 4087)","(J329, 3677)","(K219, 3663)","(M5456, 3659)","(S9349, 3613)","(H001, 3592)"
4,"(F_, 46897)","(J209, 42364)","(N_, 32992)","(J0390, 11645)","(L239, 10633)","(J304, 10063)","(J029, 9076)","(J060, 8208)","(A099, 8009)","(J00, 6645)",...,"(A_, 5237)","(K297, 5160)","(J40, 5020)","(M5456, 4955)","(N300, 4702)","(K291, 4556)","(L238, 4401)","(M5422, 4278)","(J0190, 4180)","(J_, 4166)"
5,"(N_, 53674)","(F_, 49983)","(J209, 49657)","(Z_, 16670)","(J0390, 14315)","(L239, 12206)","(J304, 11832)","(J029, 10505)","(J060, 10085)","(B_, 9847)",...,"(O_, 7068)","(J303, 7022)","(J40, 6657)","(K297, 6647)","(N300, 6512)","(S134, 6432)","(A090, 6343)","(H101, 6166)","(K291, 5773)","(J_, 5444)"
6,"(J209, 61782)","(N_, 55161)","(F_, 42333)","(Z_, 40906)","(O_, 18250)","(J0390, 15613)","(J304, 13287)","(J029, 12366)","(J060, 11420)","(L239, 10164)",...,"(M511, 7444)","(K219, 7373)","(S134, 6514)","(J0190, 6436)","(H0411, 6355)","(K297, 6322)","(A_, 6035)","(H101, 5603)","(N300, 5422)","(I109, 5371)"
7,"(J209, 90301)","(N_, 56320)","(F_, 46723)","(Z_, 30426)","(J0390, 21270)","(J304, 18612)","(I109, 17066)","(J029, 16999)","(J060, 15495)","(O_, 14631)",...,"(J303, 10069)","(K219, 9712)","(J0190, 9616)","(E119, 9091)","(A099, 8264)","(S134, 7918)","(K297, 7794)","(H101, 7445)","(H0411, 7404)","(J_, 7146)"
8,"(J209, 78969)","(N_, 51066)","(F_, 48614)","(I109, 38532)","(K210, 17802)","(J0390, 17631)","(J304, 17333)","(E119, 17140)","(M511, 14328)","(J029, 14320)",...,"(J303, 9531)","(M771, 9286)","(D_, 9201)","(H0411, 8883)","(N185, 8821)","(K297, 8629)","(S134, 8240)","(J0190, 7633)","(M501, 7217)","(Z_, 7169)"
9,"(I109, 80308)","(J209, 73719)","(N_, 53832)","(F_, 53198)","(E119, 32049)","(K210, 20572)","(M511, 17773)","(M771, 16929)","(N185, 16815)","(L239, 16248)",...,"(M750, 12254)","(M751, 12072)","(M501, 11996)","(C_, 11183)","(H0411, 11082)","(J00, 10313)","(J040, 9836)","(S134, 9734)","(K297, 9600)","(J40, 9506)"
10,"(I109, 130126)","(J209, 67812)","(F_, 52255)","(N_, 51602)","(E119, 47820)","(K210, 24571)","(N185, 22571)","(M511, 22381)","(M750, 19390)","(L239, 18712)",...,"(J0390, 13772)","(B_, 13661)","(H0411, 13333)","(J029, 12743)","(J060, 12233)","(E785, 11052)","(J40, 10715)","(N300, 10622)","(B351, 10611)","(M4806, 10439)"
11,"(I109, 189099)","(J209, 73525)","(E119, 66715)","(F_, 56418)","(N_, 37444)","(M170, 32599)","(N185, 31974)","(K210, 28056)","(M511, 27982)","(M5456, 22983)",...,"(M771, 14422)","(J0390, 14157)","(M171, 13929)","(C_, 13680)","(J029, 13464)","(M5422, 13459)","(J060, 12899)","(E118, 12867)","(B_, 12274)","(B351, 12203)"
12,"(I109, 235201)","(E119, 77857)","(J209, 76631)","(F_, 62748)","(M170, 51882)","(M4806, 36599)","(N185, 34514)","(K210, 33447)","(M511, 31088)","(N_, 27082)",...,"(M501, 16400)","(E118, 15570)","(M179, 14791)","(J304, 13867)","(J40, 13626)","(J029, 12969)","(J0390, 12936)","(J060, 12623)","(C_, 12586)","(B351, 12308)"
13,"(I109, 214517)","(E119, 67757)","(J209, 63102)","(M170, 60053)","(F_, 56135)","(M4806, 48061)","(N185, 36391)","(M5456, 28926)","(M511, 27860)","(K210, 26186)",...,"(E118, 13709)","(E785, 13590)","(J40, 11955)","(M501, 11674)","(J304, 11115)","(J00, 10618)","(M5422, 10493)","(K297, 10346)","(J029, 10283)","(J060, 10207)"
14,"(I109, 194597)","(F_, 59601)","(E119, 58231)","(M170, 56671)","(M4806, 55830)","(J209, 52696)","(N185, 39619)","(M5456, 31374)","(M511, 24575)","(N400, 24376)",...,"(J40, 10878)","(M501, 10431)","(I639, 9919)","(J304, 9869)","(J00, 9562)","(E785, 9361)","(C_, 9326)","(I209, 9232)","(K297, 9229)","(N401, 8731)"
15,"(I109, 177714)","(F_, 69903)","(M4806, 62135)","(M170, 49359)","(E119, 49223)","(J209, 43879)","(M5456, 34738)","(N185, 30377)","(M511, 21907)","(N400, 21310)",...,"(J40, 9456)","(M751, 9406)","(J00, 9232)","(M5446, 8776)","(I209, 8754)","(C_, 8607)","(S3350, 8522)","(N401, 8055)","(G20, 8006)","(J304, 7927)"
16,"(I109, 128016)","(F_, 70797)","(M4806, 42718)","(M170, 32286)","(E119, 29733)","(J209, 26915)","(M5456, 25448)","(N185, 22055)","(M511, 14004)","(N400, 12748)",...,"(I209, 6422)","(J00, 6113)","(J40, 6026)","(M750, 5998)","(C_, 5655)","(N401, 5545)","(S3350, 5492)","(K297, 5400)","(J304, 5226)","(J459, 5121)"
17,"(F_, 81133)","(I109, 78657)","(M4806, 18887)","(M170, 15329)","(E119, 13891)","(J209, 13484)","(M5456, 12156)","(N185, 9712)","(I639, 7809)","(N400, 6340)",...,"(J189, 3492)","(E118, 3401)","(J459, 3395)","(J00, 3352)","(M750, 3303)","(K219, 3208)","(I509, 3189)","(R42, 3019)","(K297, 2932)","(N401, 2757)"